# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b35f560401ebb7add3105cac924cf608b844e8a67228c8d0d162a6b5d95dfb71b45ba42f9bb11c07b2e013f82432e5fefdfdcd893cc5f91e290b08654aeb21f

test:
  secret_key_base: 911e18ed8fb2f11890a11f87b7b80bfcb881f61268a8d63e6ef502493808d051a236fb8398e0b0b71ec9735b3e06db2740d76abffba4fc1c1f7cc04e26ff8e6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
