# start at 18
Story.create!([
# 8
  {category: "origins", content: "Rosehill Cemetery (founded 1864) is an American Victorian-era cemetery on the North Side of Chicago, Illinois, and at 350 acres (1.4 km2), is the largest cemetery in the City of Chicago. The name 'Rosehill' resulted from a City Clerk's error – the area was previously called 'Roe's Hill', named for nearby farmer Hiram Roe. He refused to sell his land to the city until it was promised that the cemetery be named in his honor. It is located in the north east section of the Lincoln Square community area.

Rosehill's Joliet-limestone entrance gate was designed by William W. Boyington, the architect of the Chicago Water Tower and the Old University of Chicago, who is buried in Rosehill. The Rosehill Cemetery Administration Building and Entry Gate was listed on the U.S. National Register of Historic Places in 1975.

Like its sister cemetery Graceland, Rosehill is the burial place of many well-known Chicagoans. The cemetery contains many monuments that are notable for their beauty and eccentricity, such as that of Lulu Fellows.

Several graves from the old City Cemetery, originally located in what is now Lincoln Park were relocated to Rosehill. Some of the gravestones and monuments were also moved to Rosehill Cemetery and can be seen.", title: "Chicago’s Crown Jewel: Discovering Rosehill Cemetery"},
# 9
  {category: "origins", content: "The former Schlitz Brewery-Tied House at 1801 W. Division Street is one of the best-remaining
examples of the architecturally distinctive Chicago taverns built by breweries around the turn of
the twentieth century.
In the late-nineteenth and early-twentieth centuries, a combination of intense competition among
brewing companies and increasing legal restrictions and social pressures on public drinking
establishments compelled brewing companies in Chicago to adopt a “tied house” system.
Developed in England a century earlier, the tied-house system involved the direct control of
taverns not by independent entrepreneurs, but by large brewing companies which sold their
products exclusively at their own establishments.
Brewery control of the tavern trade in Chicago began with the purchase of existing saloon
buildings, but soon evolved into the acquisition of choice real estate and the design and
construction of tavern buildings. At least forty-one of these tied-house buildings are known to
survive in the city. They were built by large Milwaukee-based brewers, most notably Schlitz,
and by several local brewers such as the Atlas, Birk Brothers, Fortune Brothers, Gottfried,
Peter Hand, Standard, and Stege companies. In many cases, to attract customers, brewing
companies employed high-quality architectural designs and popular historical styles of
architecture for their tied houses to attract, and perhaps also to convey the legitimacy and
decency of the neighborhood tavern in the face of rising social opposition.
In addition to the tied house’s contribution to Chicago’s historic neighborhood architecture,
these buildings convey important aspects of Chicago and American history in the late-nineteenth
and early-twentieth centuries, including the large influx of European immigrants, the growth of
the vertically-integrated business model which sought to control all aspects of production from
raw material to retail sale, and the increasing political power of anti-alcohol activists. The
proliferation of tied houses in cities like Chicago was one of many factors that ultimately led to
national Prohibition in 1919.", title: "Tied House"},
# 10
  {category: "origins", content: "The Richard J. Daley Center was originally known as the Chicago Civic Center.  Located in the heart of the Chicago Loop, the Daley Center was Chicago’s first major public building to be constructed in a modern rather than a classical architectural style.  The building’s architecture is International Style and was designed by architect Jacques Brownson of C.F. Murphy Associates.  This architectural style is based on the revolutionary steel and glass skyscrapers of world-famous architect Ludwig Mies van der Rohe.

The Daley Center has 31 floors and is the tallest flat-roofed building in the world with fewer then 40 stories (a typical 648-foot building would have 50-60 stories), owing to the high ceilings needed for courtrooms.  The building has no major interior columns, only twelve exterior columns shaped in plan like a cross. These columns get narrower toward the top as they support less weight.  It has 87-foot steel trusses running lengthwise and 48-foot spans running crosswise, at the time unprecedented in their dimensions.  The structural bays, (87-feet) are so wide that they are often compared to bridges.  The building was the first ever to be clad with untreated Corrosive Tensile (Cor-Ten) steel. Designed to rust overtime, the steel actually strengthens the structure and develops a natural rust patina giving the Daley Center its distinctive red and brown color.

The Daley Center was built to house more than 120 court and hearing rooms, the Cook County Law Library and office space for the City and Cook County.  It was built by the Chicago Public Building Commission and financed by revenue bonds.  The $87 million project was started February 28, 1963 and the first occupants moved into the Daley Center in May 1965.  The Chicago Civic Center was renamed the Richard J. Daley Center, Richard J. Daley Plaza, on December 27, 1976 in honor of the late Mayor who died in office on ", title: "Plaza Gem"},
# 11
  {category: "origins", content: "A National Historic Landmark, the Auditorium Theatre is known internationally for its perfect acoustics, innovative architecture and stunning design.

The Auditorium Theatre began with a Chicago business man named Ferdinand Wythe Peck.  He was dedicated to improving the city of Chicago and after the Haymarket Square riot in 1886 he began plans for the Auditorium Building, that included the theatre, as well as an office block and hotel. He envisioned a theatre for all Chicagoans, and incorporates the Chicago Auditorium Association for the purpose of developing the world’s largest, grandest, most expensive building.

The famous architectural firm of Adler and Sullivan designed this 4,000 seat theatre in 1889 using modern technology, including electric lighting and air conditioning. They pushed the limits of modern architecture to make the Auditorium the tallest building in Chicago, the first multi-use building ever designed and the most massive modern edifice in the world for its time.

Though the Auditorium opened to immense critical acclaim, what began as a masterfully-designed opera house that sprang from the minds of geniuses gradually fell into disrepair. For decades the Auditorium Theatre continued its decline before experiencing an astounding resurgence in the 1960’s, and ultimately returning to its former status as a jewel in American history.

Thanks to multiple restoration and conservation projects, visitors again enjoy the radiant 24-karat gold-leafed ceiling arches, hundreds of Sullivan’s beautifully restored intricate stencil patterns, ornate gilded and bas-relief designs, and the endless floor and wall mosaics and murals by Charles Holloway and Albert Fleury.

", title: "Auditorium"},
# 12
  {category: "origins", content: "Born in Cedarville, Illinois, on September 6, 1860, and graduated from Rockford Female Seminary in 1881, Jane Addams founded, with Ellen Gates Starr, the world famous social settlement Hull-House on Chicago's Near West Side in 1889. From Hull-House, where she lived and worked until her death in 1935, Jane Addams built her reputation as the country's most prominent woman through her writing, settlement work, and international efforts for peace.

Social settlements began in the 1880s in London in response to problems created by urbanization, industrialization, and immigration. The idea spread to other industrialized countries. Settlement houses typically attracted educated, native born, middle-class and upper-middle class women and men, known as “residents,” to live (settle) in poor urban neighborhoods. Some social settlements were linked to religious institutions. Others, like Hull-House, were secular. By 1900, the U.S. had over 100 settlement houses. By 1911, Chicago had 35.

In the 1890s, Hull-House was located in the midst of a densely populated urban neighborhood peopled by Italian, Irish, German, Greek, Bohemian, and Russian and Polish Jewish immigrants. During the 1920s, African Americans and Mexicans began to put down roots in the neighborhood and joined the clubs and activities at Hull-House. Jane Addams and the Hull-House residents provided kindergarten and day care facilities for the children of working mothers; an employment bureau; an art gallery; libraries; English and citizenship classes; and theater, music and art classes. As the complex expanded to include thirteen buildings, Hull-House supported more clubs and activities such as a Labor Museum, the Jane Club for single working girls, meeting places for trade union groups, and a wide array of cultural events.

The residents of Hull-House formed an impressive group, including Jane Addams, Ellen Gates Starr, Florence Kelley, Dr. Alice Hamilton, Julia Lathrop, Sophonisba Breckinridge, and Grace and Edith Abbott. From their experiences in the Hull-House neighborhood, the Hull-House residents and their supporters forged a powerful reform movement. Among the projects that they helped launch were the Immigrants' Protective League, the Juvenile Protective Association, the first juvenile court in the nation, and a Juvenile Psychopathic Clinic (later called the Institute for Juvenile Research). Through their efforts, the Illinois Legislature enacted protective legislation for women and children in 1893. With the creation of the Federal Children's Bureau in 1912 and the passage of a federal child labor law in 1916, the Hull-House reformers saw their efforts expanded to the national level.

Jane Addams wrote prolifically on topics related to Hull-House activities, producing eleven books and numerous articles as well as maintaining an active speaking schedule nationwide and throughout the world. She played an important role in many local and national organizations. A founder of the Chicago Federation of Settlements in 1894, she also helped to establish the National Federation of Settlements and Neighborhood Centers in 1911. She was a leader in the Consumers League and served as the first woman president of the National Conference of Charities and Corrections (later the National Conference of Social Work). She was chair of the Labor Committee of the General Federation of Women's Clubs, vice-president of the Campfire Girls, and a member of the executive boards of the National Playground Association and the National Child Labor Committee. In addition, she actively supported the campaign for woman suffrage and the founding of the National Association for the Advancement of Colored People (1909) and the American Civil Liberties Union (1920).

In the early years of the twentieth century Jane Addams became involved in the peace movement. During the First World War, she and other women from belligerent and neutral nations met at the International Congress of Women at the Hague in 1915, attempting to stop the war. She maintained her pacifist stance after the United States entered the war in 1917, working to found the Women's Peace Party (WILPF), which became the Women's International League for Peace and Freedom in 1919. She was the WILPF's first president. As a result of her work, she was awarded the Nobel Peace Prize in 1931.

Jane Addams died in Chicago on May 21, 1935. She was buried in Cedarville, her childhood home town.", title: "Hull House"},
# 13
  {category: "origins", content: "The architecture of the Pittsfield Building was designed with two different commercial spaces. The upper floors, from 5 to 37, were professional offices for lawyers, dentists, and doctors. The lower levels, from the basement to the 5th, were for small retailers such as jewelers, restaurants, tobacco stores, and newsstands.

The lower levels were decorated in a “Spanish Gothic Revival” style with some Art Deco touches. The architectural style unmistakably recalls the 1920’s, which gives you a taste of history. When you step inside, the gilt elevator lobby ceilings are coffered into a maze-like hexagonal pattern. Continue entering, and the atrium soars five floors above you and is crowned with a gigantic chandelier. Every spare surface in the lobby and atrium seems to be covered in marble. The beauty of this space makes the Pittsfield a rental for the occasional wedding.

The effect of all the architectural ornamentation is stunning in its opulence and aesthetic appeal. Of course, that fits right into the flashy architectural approach that Marshall Field pioneered at his store, as any of our Loop Interior Architecture Walking Tour guests can attest. It’s easy to see why the building was declared a Chicago Historic Landmark in 2002.", title: "THE PITTSFIELD BUILDING’S ARCHITECTURE, PAST TO PRESENT"},
# 14
  {category: "origins", content: "Elam House was owned by Mrs. Melissia Ann Elam. She was born in Missouri in 1853; her parents were slaves. After Emancipation, she moved to Chicago and worked as a maid until she married realtor Rubin Elam. Seeing the tremendous need for housing and guidance for the many single African American girls and women migrating into the city, Mrs. Elam purchased a home at 4555 South Champlain in 1923 and opened it as the Melissia Anne Elam Home for Working Women and Girls. Mrs. Elam and Isadore Anna Drell purchased the home at 4726 South Park Way in 1926, when demand outgrew space in the Champlain residence. Between the 1930s and the 1950s, Elam Home often housed over 30 women and girls at a time. The home was also the center of many Black, civic, social, and cultural events, including a state convention for African American women.

Mrs. Elam died in 1941 and her niece Loretta Peyton took over as trustee of the home. Mrs. Elam willed Elam House to Centers for New Horizons, Inc. Centers for New Horizons is a not for profit social service agency that serves the Bronzeville and Riverdale communities on the Southside of Chicago, Illinois. Ms. Elam stipulated to Centers for New Horizons in her will that her home be kept in service to the community. She entrusted the home to a group of African American women, who maintained the home as a boarding home. As times changed, fewer women sought housing in boarding homes like Mrs. Elam’s, and the population of Elam House declined, although several women continued to live there well into the 1970s. The Friends of Elam House Foundation was created in 1974 by Margaret Burroughs. At risk of being torn down due to numerous building violations, the Friends of Elam House Foundation raised funds to address these violations and try to attain landmark status. The DuSable Museum of African American History was named trustee of the foundation and in 1979 the home was declared a Chicago Historical Landmark.

", title: "Elam House"},
# 15
  {category: "origins", content: "October 30, 1893 is the last day of Chicago’s World’s Columbian Exposition, a great fair that celebrated the 400th anniversary of Columbus’s arrival in the New World and offered fairgoers a chance to see the first gas-powered motorcar in the United States: the Daimler quadricycle. The exposition introduced Americans to all kinds of technological wonders—for instance, an alternating-current power plant, a 46-foot-long cannon, a 1,500-pound Venus de Milo made of chocolate, and Juicy Fruit gum—along with replicas of exotic places and carnival-style rides and games.

Four years earlier, the Universal Exposition in Paris had featured an elaborate display of steam- and gas-powered vehicles, including the Serpollet-Peugeot steam tricar, named for its three wheels and powered by a coke-burning boiler and a lightweight, petrol-fueled four-wheeled car built by the German engineer Gottlieb Daimler. The Chicago fair promised an even more impressive spectacle. Its Transportation Building, designed by Louis Sullivan, was crammed full: Pack mules and horse-drawn carts crowded next to bicycles and boats. Most exciting of all were the rows of massive American-built steam locomotives that towered over everything else in the hall. Trains, the Exposition’s organizers seemed to say, were the transportation of the future.

Only one internal-combustion vehicle was on display at the fair, tucked away in the corner of the Transportation Building: another of the wire-wheeled, tiller-steered, one-cylinder platform quadricycles that Daimler had introduced to Parisian fairgoers in 1889. It was like nothing most Americans had ever seen and yet almost no one paid any attention to it. Reporters barely mentioned the Daimler car and it didn’t even appear in the exhibition catalog.

But a few very important people did notice it and studied it closely. One was the bicycle mechanic Charles Duryea, who used the Daimler car as the inspiration for the four-wheeled, one-cylinder Motor Wagon that he built with his brother Frank. In 1896, the Duryea Motor Wagon Company became the first company to mass-produce gas-powered vehicles in the United States.

Another admirer of the Daimler car was Henry Ford, who returned to Dearborn after the fair and built an internal-combustion quadricycle of his own. (He called it his “gasoline buggy.”) Ford drove his little car for the first time on July 4, 1896 and sold it later that year for $200. Just a few years later, he incorporated the Ford Motor Company and the automobile age had begun.", title: "The World’s Columbian Exposition closes in Chicago"},
# 16
  {category: "origins", content: "This corner lot was used by the community for Independence Day picnics from 1875. However, in 1888 it was purchased by Dr. Wallace Abbott, a local doctor and pharmacist. He commissioned Rudolph Dahlgren and Oscar Livendahl to design the current home. It was completed in 1891.

Dr. Abbott had gotten his start in his pharmacy and medical office, located on Ravenswood Avenue, manufacturing the first medications in his kitchen apartment. The company he founded, Abbott Labs, moved with the family to this location in 1891, then the company moved to the first of several properties on Ravenswood.
The company sites were known for several spectacular fires as well as industrial accidents leading it to move in 1925 to rural North Chicago.
Dr. Abbott could boast of owning an early telephone, among the first on the North Side. It’s simple number was Lake View 143.
The 1900 Census notes Dr. Abbott, his wife Clara, their daughter, Dr. Abbott’s father, a cook a nurse girl and a stableman.
The Abbott Mansion during the years it struggled. 

Dr. Abbott died on his way home from the office one day in July 1921.
The Abbotts moved in 1925, selling the building to the Maginot family. They used the building as the Maginot Funeral Home for many years.
A 1983 story in Crain’s Chicago Business notes the then owners, not the Maginot’s, had purchased the mansion after it had gone through several owners. They had, the story notes, spent six years and $100,000 to attempt to restore the building.
“The Abbott House contains 15 rooms and seven bathrooms and boasts a 1,300 square foot front room,” the story notes.
A Chicago Magazine story has more information, noting the Maginot family had sold the property in the 1970’s. In 2004 Abbott Labs took possession of the property for $1.5 million.

Abbott Labs cloned the property, according to Chicago Magazine, removing the front door, a fireplace mantel, some stained glass and a stepping stone engraved with the name Wallace Abbott.
The second Abbott mansion exists on the company’s campus in North Chicago.
After being awarded a Chicago Landmark Award for Preservation Excellence by the Commission on Chicago Landmarks in 2006, the home was sold by Abbott Labs for $1.95 million.
The home was last sold in 2011 for $1,606,000.
", title: "Abbott House"},
# 17
  {category: "origins", content: "The Palmolive Building, formerly the Playboy Building, is a 37-storey Art Deco building at 919 N. Michigan Avenue in Chicago. Built by Holabird & Root, it was completed in 1929 and was home to the Colgate-Palmolive-Peet corporation.

The Palmolive Building was renamed the Playboy Building in 1965 when Playboy Enterprises purchased the leasehold of the building. It was home to the editorial and business offices of Playboy magazine from that time until 1989 when Playboy moved its offices to 680 N Lake Shore Drive. Playboy had sold the leasehold in 1980 and signed a 10-year lease that expired in 1990. The new leaseholder renamed the building 919 North Michigan Avenue.

During the time that Playboy was in the building, the word P-L-A-Y-B-O-Y was spelled out in 9-foot (2.7 m) illuminated letters. The building was designated a Chicago Landmark in 2000, and it was added to the federal National Register of Historic Places in 2003.

In 2001, the building was sold to developer Draper and Kramer who, with Booth Hansen Architects, converted it to residential use with the first two floors dedicated to upscale office and retail space. High-end condos make up the rest of the building. The new owners restored the building's name to the Palmolive Building. The business address remains 919 North Michigan Avenue; however, the residential address is 159 East Walton Street. Notable residents of the building include Vince Vaughn, who bought a 12,000-square-foot triplex penthouse encompassing the 35th, 36th and 37th floors for $12,000,000. In February 2013, Vaughn offered the penthouse for sale as a pocket listing for $24.9 million. However, after multiple price cuts he chose in May 2016 to divide the unit in two, offering one for $8.5 million, and the other smaller unit for $4.2 million.", title: "Palmolive Building"},


 # 8
  {category: "chicago", content: "The Democratic National Convention of 1864 was by most accounts a disaster. Meeting in Chicago to nominate General McClellan to oppose Lincoln,  the party struggled with an unhealed rift between delegats who wanted to crush the Confederacy in one big blow and those who wanted to quit fighting and just let the South go. The Tribune’s coverage made the convention look like a regular amateur hour.

But one man was more impressed: Wilbur F. Storey, arch-conservative editor of the Lincoln-hating Chicago Times. A year before, when he described Lincoln’s speech at Gettysburg as “silly, flat and dishwatery utterances,” he was being relatively subdued in his criticism. Months before, he had said that “history does not acquaint us with so deplorable a failure as this administration,” and held up the coming Emancipation Proclamation as proof of what he’d said all along: that Lincoln was coming to take people’s slaves. This was no war to preserve the union, he said, but a contest to free  “the debased and irredeemably barbarous negro.” (1) The proclamation itself, he said “Will be known in all history as the most wicked, atrocious and revolting deed recorded in the annals of civilization.”(2) (That the war was something to do with states’ rights would not become a conservative talking point for decades).

Even this was not Storey at his worst. Though far more loquacious than most modern cable news loudmouths, some of his racial ramblings would fit in fine among alt-right commenters on youtube. In 1862 he complained that rather than caring about the rights of white men, congress had “n—r on the brain, n—r in the bowels, n—r in the eyes, n—r, n—r everywhere….all powers have found their superior in the great n—r power that moves the huge, unwieldy, reeking and stewing mess of rottenness which makes up this administration and its party.” (3) Though it’s common now for detractors to claim that Lincoln didn’t do enough for the slaves, or that he was really just as big of a racist as any slave-holder, Storey’s rants (and his paper’s popularity) can be useful in showing just what Lincoln was up against.

Naturally, Storey supported McClellan in 1864, and covered the Democrat Convention as though it was the Second Coming (it’s useful to note that the parties of 1864 were very different; Storey referred to his party as both “The democrats” and “conservatives,” while referring to republicans as “the abolitionist party.”) Its in his election coverage that Storey’s rants and language seem most strikingly modern in 2016. Months before the convention, he’d suggested that Lincoln was going to rig the election and refuse to allow conservatives to vote. In an August 31, 1864 editorial, “Plots of Old Abe,” he doubled down on the claim. “The machinery for carrying out the… plot is in readiness,” he wrote. “It will certainly be applied unless, in the interim, the people of Illinois assume such an attitude as will convince the tyrant that there is one step that he cannot with safety take. Let it be understood that… any attempt on the part of the despot to do otherwise (than conduct a fair election) will surely lead to bloodshed, and, perhaps, even at the last moment, the attempt to coerce Illinois may be abandoned.", title: "“Rigged!” The Chicago Times and the Election of 1864"},
# 9
  {category: "chicago", content: "Too many of Chicago's cops weren't doing their jobs. Slouching in unkempt uniforms, they drank whiskey in saloons when they should have been walking their beats. And they ignored crimes happening right in front of their eyes.

These were the findings of an investigation in 1904 called the Piper Report. Chicago's police department was given the most unmerciful raking in its history, the Tribune reported at the time.
More than a century before a recent U.S. Department of Justice report excoriated the Chicago Police Department for widespread failures, Chicago police faced scrutiny from an outside investigator.

The condition is 'rotten,' said Louis Grossman, a Chicago private eye who worked on the 1904 report. The police of Chicago are 'piano movers,' bums, cripples, janitors, ward heelers — anything but policemen. They have no respect for the law, and depend upon their pull with the alderman to get them out of trouble. Out of all the precincts we have watched, we have found but two patrolmen who did their duty. They sleep when they should be on their rounds. They play the slot machines and drink with any one who asks them.

The probe was led by retired Army Capt. Alexander Piper, a graduate of the U.S. Military Academy who'd fought in battles against Sioux Indians and in the Spanish-American War. Piper, who'd lost his right arm to a gunshot, had also served as a New York City police official.
In early 1904, the City Club of Chicago hired him to snoop on Chicago's police. That civic group, known today for hosting political speeches, had just formed in December 1903. For months, newspapers had been filled with headlines about murders and holdups. Meanwhile, a committee of aldermen was investigating graft, hearing testimony about cops allegedly taking protection money from prostitutes and criminals. The police superintendent, Francis O'Neill, had a reputation for honesty, but he faced criticism for allowing corruption and inaction.

Chicago's cops weren't yet represented by a union, but in January 1904 they formed a protective association, raising money to defend officers facing misconduct accusations. Tribune editorials denounced the association's hostility to investigation, calling it a slush fund to hide corruption.
Piper and two investigators spent six weeks visiting police stations, walking streets and watching cops. They saw 174 incidents they described as dereliction of duty, including on-duty officers drinking in taverns. William Maher, one of Piper's assistants, wrote in the report that he didn't see any cops pay for their drinks. They thought nothing of going off post to get a shave, taking off their hats and sitting down for an hour, or going into a concert saloon, seeing women solicit men for the purpose of prostitution in their presence, he said.
One police official explained to Piper why a cop should visit saloons: By going there he can become friendly with the saloonkeeper and obtain information about criminals that he could not get elsewhere.", title: "Chicago police were condemned in 1904 for drinking, slouching, ignoring crime"},
# 10
  {category: "chicago", content: "he Chicago Freedom Movement, led by Dr. Martin Luther King Jr., James Bevel, and Al Raby, was created to challenge systematic racial segregation and discrimination in Chicago and its suburbs. The movement which included rallies, protest marches, boycotts, and other forms of non-violent direct action addressed a variety of issues facing black Chicago residents, including segregated housing, educational deficiencies, income, employment, and health disparities based on racism and black community development. The Chicago Freedom Movement, the most ambitious civil rights campaign in the northern United States, lasted from mid-1965 to early 1967 and is credited with inspiring the Fair Housing Act passed by the U.S. Congress in 1968.  
The Chicago Campaign began in July 1965 when local civil rights groups invited Dr. King to lead demonstrations against segregation in education and housing as well as employment discrimination. Chicago activist Albert Raby, leader of the Coordinating Council of Community Organizations (CCCO), asked the Southern Christian Leadership Conference (SCLC) to join them in a nonviolent campaign to achieve fair or open housing in the city. Community organizers pointed to Chicago’s history as one of the most racially segregated cities in the nation. Through lending discrimination and, in some instances, outright violence and intimidation, African Americans were kept out of the vast majority of predominately or all-white middle class neighborhoods in the city. Activists hoped that by changing the laws and practices to allow “open housing,” the ability of black homeowners to purchase homes in any area they could financially afford, blacks would gain access to improved housing, better schools, and greater job opportunities.  

On January 7, 1966, King and the SCLC announced plans for a Chicago Freedom Movement, a campaign that marked the expansion of their civil rights activities from the South to northern cites. King and his family moved to a Chicago slum at the end of January to bring attention to housing conditions of tens of thousands of black Chicago residents while CCCO organized mass nonviolent protests in the city.

To target racial demonstration in housing and employment, SCLC launched Operation Breadbasket and placed it under the leadership of twenty-five-year-old SCLC organizer, Rev. Jessie Jackson. Operation Breadbasket targeted companies and corporations working in African American neighborhoods that nonetheless refused to hire black employees. The parallel campaigns gained momentum through boycotts, demonstrations, marches, and the race riots that erupted on Chicago’s predominately black West Side in July 1966. On August 5, 1966, during a march at Marquette Park, an all-white Chicago neighborhood, to promote open housing, black and white demonstrators were met with intense racially-fueled hostility. Bottles and bricks were thrown at them. Dr. King, leader of the march, was struck by a rock. King admitted in a post-march interview that he had seen many anti-civil rights demonstrations in the South but none that was as hostile and violent as the one he experienced in Marquette Park.

King faced the challenge of mobilizing Chicago’s diverse African American community of nearly one million people. He cautioned against further violence and worked to counter the mounting resistance of working class whites who were fearful of the impact of open housing on their neighborhoods. By August, Chicago Mayor Richard Daley sought a way to end the demonstrations. After negotiating with King and various housing boards, an agreement was announced on August 26, 1966, in which the Chicago Housing Authority promised to build public housing in predominately white areas, and the Mortgage Bankers Association agreed to make mortgages available, regardless of race or neighborhood. After the agreement was announced, some SCLC staff stayed behind to assist with the housing programs and voter registration. Dr. King stayed in Chicago until January 1967, while Jackson settled permanently in the city to lead the Chicago branch of Operation Breadbasket. In 1968 the U.S. Congress passed the 1968 Fair Housing Act, as the most direct result of the Chicago Freedom Movement.", title: "Chicago Freedom Movement"},
# 11
  {category: "chicago", content: "On this night in 1871, fire breaks out in a barn behind the Chicago cottage of Patrick O’Leary. Winds blowing off the prairie fed the flames, and the fire spread rapidly, eventually consuming a four-mile-long and two-third-mile-wide swath of Chicago. When the Great Fire was finally over two days later, nearly 300 people were dead, one hundred thousand were homeless, and Chicago’s booming downtown was in ashes. Despite the devastation, Chicago would rise again and continue to be the economic center of the American West for decades to come.

Most people think of Chicago as a midwestern city, and geographically it obviously is. But economically, Chicago is best seen as the unofficial regional capital and economic center of the American West. Because of its location on the western edge of a system of lakes, rivers, and canals that linked the city to the East, Chicago was the natural destination for both western raw materials moving East and eastern manufactured goods moving West. After the Civil War, Chicago quickly eclipsed St. Louis as the primary trading hub between East and West, and the city’s fate was inextricably tied to the rapidly growing settlement and development of western natural resources. Millions of dollars worth of cattle, lumber, swine, and grain that had originated in the plains of Wyoming or the mountains of Montana were channeled through the massive freight yards, slaughterhouses, and grain elevators of Chicago. Indeed, a look at a map of the U.S. during the 1880s revealed that while all roads may have once led to Rome, by the late 19th century all railroads led to Chicago.

Although the Great Fire of 1871 destroyed Chicago’s downtown, it left most of the city’s essential industrial infrastructure in place. Scarcely missing a beat, the towering grain elevators and vast stockyards continued to collect the growing output of the West, process it into pork sausages or two-by-fours, and send it onward to the insatiable markets of the East.", title: "Chicago fire"},
# 12
  {category: "chicago", content: "Paul M. Angle has certainly succeeded in producing a unique work; namely, a history of a historical society which is witty, readable, and, at the same time, informative and factually accurate. He has accomplished this result by a skillful selection of letters, documents, and news clippings which he allows to speak for themselves, with but brief introductions and comments. It is a work of stark impressionism, done with broad strokes and in vivid colors. In consequence, it communicates to the reader a sense of identification with events in the life of the Chicago Historical Society and of Chicago which no dry chronological record of the minutiae of society records could possibly accomplish. It stimulates the imagination of the reader to cooperate with the author to amplify his pungent comments. There is a laugh on nearly every page.

Of course, no one could tell the tale of the Chicago Historical Society in the first century of its life (1856–1956) without reflecting the highlights of Chicago history in this fabulous era when Chicago was transformed from a crude trading village set in a wilderness to a mighty metropolis; the true capital of the Middle West; the financial center of the richest empire the world has even known; and a formidable cultural and educational venture.

The only astonishing phenomenon is that, considering the vast effort necessarily expended in this century by the citizens of Chicago in the material realm, they had energy left to cultivate the arts and foresight to document their history in the making by supporting so generously their historical society and accumulating the documents, letters, books, and records which perpetuate their experiences.

In the great Chicago fires of 1871 and 1874 the Society's building and all of its original collections were destroyed, including two thousand volumes of sermons with which the more pious early inhabitants seem to have endowed the library. But the Society arose from the ashes, and in the ensuing seventy-five years has accumulated a distinguished library and collection of invaluable historical source material contained in a beautiful building of noble proportions, in which likewise is housed a museum which displays & visual pageant of Chicago's history. The vigilance of the Society's officers is to be commended, particularly in their solicitation in 1882 of a gift of the Lincoln papers then in the custody of Robert Todd Lincoln, who, in his reply to the Society (August 27, 1882) made one of the most colossal understatements of all times when he said: " 'In reply to your letter of August 7th respecting the custody of letters and documents received and preserved by my father and mother, I have to say to you that the idea of placing them in the custody of the Historical Society would strike me with favor if there were anything of sufficient consequence to include in such a collection. …' "

While the Society acquired none of the Washington papers, we are relieved to learn that it has one of his razors. Amongst its more gruesome artifacts are the bones of John Lalime, one of the earliest settlers of Chicago. But the Society felt obliged to decline, in 1943, the preferred gift by Sally Rand of the fan which she used so effectively in her famous dances at the Chicago World's Fair of 1933. The Chicago Daily News headline of this event is duly recorded: Sally Rand pitches curves to fan Historical Society.

Angle modestly described his work as an unconventional chronicle. And so it is. But it will be read with chuckles by succeeding generations, which is more than can be said of the mine run of society histories.

The book is a most attractive example of printing and binding, and contains a serviceable index.", title: "The Chicago Historical Society"},
# 13
  {category: "chicago", content: "On January 7, 1927, the Harlem Globetrotters basketball team travels 48 miles west from Chicago to play their first game in Hinckley, Illinois.

The Globetrotters were the creation of Abe Saperstein of Chicago, who took over coaching duties for a team of African-American players originally known as the Savoy Big Five (after the famous Chicago ballroom where they played their early games). At a time when only whites were allowed to play on professional basketball teams, Saperstein decided to promote his new team’s racial makeup by naming them after Harlem, the famous African-American neighborhood of New York City. The son of a tailor, Saperstein sewed their red, white and blue uniforms (emblazoned with the words “New York”) himself. The lineup in that first game, for which the Globetrotters were paid $75, was Walter “Toots” Wright, Byron “Fat” Long, Willis “Kid” Oliver, Andy Washington and Al “Runt” Pullins.

The Globetrotters won 101 out of 117 games that first season and introduced many Midwestern audiences to a game they had not seen played before. As owner, coach, manager, publicist and sometimes even substitute player, Saperstein worked overtime to book games for his team. By 1936, they had played more than 1,000 games and appeared in Wisconsin, Minnesota, Iowa, Michigan, Montana, Washington and North and South Dakota. (The Globetrotters didn’t actually play a game in Harlem until the late 1960s.) Their first national championship appearance came in 1939, when the Globetrotters lost to the New York Renaissance. That same year, the team began to add the silly antics they later became known for, including ball handling tricks and on-court comedic routines. The crowds loved it, and Saperstein told his team to keep up the clowning around, but only when they had achieved a solid lead.

In 1948, the Globetrotters earned a new measure of respect by beating the Minneapolis Lakers of the newly established National Basketball Association (NBA). Two years later, the NBA lifted its “whites only” ban and began to draft black players, forcing Saperstein to compete for his talent. By this time, the Globetrotters were actively touring on the international circuit, playing to audiences in post-war Berlin, Eastern Europe and Russia, among other places; they even performed once for Pope Pius XII in Rome. Some of the Globetrotters who went on to become NBA stars include Wilt Chamberlain, Connie Hawkins and Nat Clifton.

After Saperstein’s death in 1966, the team was sold to a group of Chicago businessmen for $3.7 million; they later sold it to Metro Media for $11 million. Reaching the height of their fame in the 1970s, the Globetrotters began to lose fans during the next decade, after the departure of such longtime stars as Meadowlark Lemmon. In 1985, Olympic gold medalist Lynette Woodard became the first female Globetrotter.

Over the years, the Harlem Globetrotters have played in more than 115 countries in front of 120 million fans. They have been the subject of two feature films and numerous television shows, including two animated series in the 1970s. In honor of their entertainment value, the team was awarded a star on the Hollywood Walk of Fame and made the subject of a permanent exhibit at the Smithsonian Institute. Their pioneering history and considerable athletic skill over the years was honored in 2002, when they were inducted into the Basketball Hall of Fame.

  by Taboola Promoted Links 
", title: "Harlem Globetrotters play their first game"},
# 14
  {category: "chicago", content: "A fire in the Iroquois Theater in Chicago, Illinois, kills more than 600 people on this day in 1903. It was the deadliest theater fire in U.S. history. Blocked fire exits and the lack of a fire-safety plan caused most of the deaths.

The Iroquois Theater, designed by Benjamin Marshall in a Renaissance style, was highly luxurious and had been deemed fireproof upon its opening in 1903. In fact, George Williams, Chicago’s building commissioner, and fire inspector Ed Laughlin looked over the theater in November 1903 and declared that it was “fireproof beyond all doubt.” They also noted its 30 exits, 27 of which were double doors. However, at the same time, William Clendenin, the editor of Fireproof magazine, also inspected the Iroquois and wrote a scathing editorial about its fire dangers, pointing out that there was a great deal of wood trim, no fire alarm and no sprinkler system over the stage.

During the matinee performance of December 30, while a full house was watching Eddie Foy star in Mr. Bluebeard, 27 of the theater’s 30 exits were locked. In addition, stage manager Bill Carlton went out front to watch the show with the 2,000 patrons while the other stage hands left the theater and went out for a drink. It was a spotlight operator who first noticed that one of the calcium lights seemed to have sparked a fire backstage. The cluttered area was full of fire fuel–wooden stage props and oily rags.

When the actors became aware of the fire, they scattered backstage; Foy later returned and tried to calm the audience, telling them to stay seated. An asbestos curtain was to be lowered that would confine the fire but when it wouldn’t come fully down, a panic began. It later turned out to be made of paper so it wouldn’t have helped in any case. Soon, all the lights inside the theater went out and there were stampedes near the open exits. When the back door was opened, the shift of air caused a fireball to roar through the backstage area.

The teenage ushers working the theater fled immediately, forgetting to open the locked emergency exit doors. The few doors that were able to be forced open were four feet above the sidewalk, which slowed down the exiting process. Most of the 591 people who died were seated in the balconies. There were no fire escapes or ladders to assist them and some took their chances and jumped. The bodies were piled six deep near the narrow balcony exits. In fact, some people were knocked down by the falling bodies and were eventually pulled out alive from under burned victims.

In the aftermath of the disaster, Williams was later charged and convicted of misfeasance. Chicago’s mayor was also indicted, though the charges didn’t stick. The theater owner was convicted of manslaughter due to the poor safety provisions; the conviction was later appealed and reversed. In fact, the only person to serve any jail time in relation to this disaster was a nearby saloon owner who had robbed the dead bodies while his establishment served as a makeshift morgue following the fire.", title: "Fire breaks out in Chicago theater"},
# 16
  {category: "chicago", content: "October 30, 1893 is the last day of Chicago’s World’s Columbian Exposition, a great fair that celebrated the 400th anniversary of Columbus’s arrival in the New World and offered fairgoers a chance to see the first gas-powered motorcar in the United States: the Daimler quadricycle. The exposition introduced Americans to all kinds of technological wonders—for instance, an alternating-current power plant, a 46-foot-long cannon, a 1,500-pound Venus de Milo made of chocolate, and Juicy Fruit gum—along with replicas of exotic places and carnival-style rides and games.

Four years earlier, the Universal Exposition in Paris had featured an elaborate display of steam- and gas-powered vehicles, including the Serpollet-Peugeot steam tricar, named for its three wheels and powered by a coke-burning boiler and a lightweight, petrol-fueled four-wheeled car built by the German engineer Gottlieb Daimler. The Chicago fair promised an even more impressive spectacle. Its Transportation Building, designed by Louis Sullivan, was crammed full: Pack mules and horse-drawn carts crowded next to bicycles and boats. Most exciting of all were the rows of massive American-built steam locomotives that towered over everything else in the hall. Trains, the Exposition’s organizers seemed to say, were the transportation of the future.

Only one internal-combustion vehicle was on display at the fair, tucked away in the corner of the Transportation Building: another of the wire-wheeled, tiller-steered, one-cylinder platform quadricycles that Daimler had introduced to Parisian fairgoers in 1889. It was like nothing most Americans had ever seen and yet almost no one paid any attention to it. Reporters barely mentioned the Daimler car and it didn’t even appear in the exhibition catalog.

But a few very important people did notice it and studied it closely. One was the bicycle mechanic Charles Duryea, who used the Daimler car as the inspiration for the four-wheeled, one-cylinder Motor Wagon that he built with his brother Frank. In 1896, the Duryea Motor Wagon Company became the first company to mass-produce gas-powered vehicles in the United States.

Another admirer of the Daimler car was Henry Ford, who returned to Dearborn after the fair and built an internal-combustion quadricycle of his own. (He called it his “gasoline buggy.”) Ford drove his little car for the first time on July 4, 1896 and sold it later that year for $200. Just a few years later, he incorporated the Ford Motor Company and the automobile age had begun.", title: "The World’s Columbian Exposition closes in Chicago"},
  {category: "chicago", content: "October 30, 1893 is the last day of Chicago’s World’s Columbian Exposition, a great fair that celebrated the 400th anniversary of Columbus’s arrival in the New World and offered fairgoers a chance to see the first gas-powered motorcar in the United States: the Daimler quadricycle. The exposition introduced Americans to all kinds of technological wonders—for instance, an alternating-current power plant, a 46-foot-long cannon, a 1,500-pound Venus de Milo made of chocolate, and Juicy Fruit gum—along with replicas of exotic places and carnival-style rides and games.

Four years earlier, the Universal Exposition in Paris had featured an elaborate display of steam- and gas-powered vehicles, including the Serpollet-Peugeot steam tricar, named for its three wheels and powered by a coke-burning boiler and a lightweight, petrol-fueled four-wheeled car built by the German engineer Gottlieb Daimler. The Chicago fair promised an even more impressive spectacle. Its Transportation Building, designed by Louis Sullivan, was crammed full: Pack mules and horse-drawn carts crowded next to bicycles and boats. Most exciting of all were the rows of massive American-built steam locomotives that towered over everything else in the hall. Trains, the Exposition’s organizers seemed to say, were the transportation of the future.

Only one internal-combustion vehicle was on display at the fair, tucked away in the corner of the Transportation Building: another of the wire-wheeled, tiller-steered, one-cylinder platform quadricycles that Daimler had introduced to Parisian fairgoers in 1889. It was like nothing most Americans had ever seen and yet almost no one paid any attention to it. Reporters barely mentioned the Daimler car and it didn’t even appear in the exhibition catalog.

But a few very important people did notice it and studied it closely. One was the bicycle mechanic Charles Duryea, who used the Daimler car as the inspiration for the four-wheeled, one-cylinder Motor Wagon that he built with his brother Frank. In 1896, the Duryea Motor Wagon Company became the first company to mass-produce gas-powered vehicles in the United States.

Another admirer of the Daimler car was Henry Ford, who returned to Dearborn after the fair and built an internal-combustion quadricycle of his own. (He called it his “gasoline buggy.”) Ford drove his little car for the first time on July 4, 1896 and sold it later that year for $200. Just a few years later, he incorporated the Ford Motor Company and the automobile age had begun.", title: "Columbia"},
# 17
  {category: "chicago", content: "Jack Dempsey, the “Manassa Mauler,” misses an opportunity to regain the heavyweight boxing title when he fails to return to a neutral corner after knocking down champ Gene Tunney in a title match in Chicago. Dempsey waited five precious seconds before heading to the neutral corner, at which point the referee began the 10-count as the rules dictated. As the referee reached nine seconds, Tunney got back up to his feet. He had actually been down for what amounted to 14 seconds. Tunney went on to win the bout in a decision after 10 rounds.

Jack Dempsey, one of the most formidable and popular boxers of all time, was born in Manassa, Colorado, in 1895. One of 11 children, he left home at age 16 and traveled around Colorado’s mining towns, earning a living boxing under the name of “Kid Blackie.” In 1916, he abandoned saloon-floor matches in favor of professional bouts and earned a reputation as a quick and lethal fighter who generally knocked out his opponents at some point in the first round.

By 1919, Dempsey earned a fight with heavyweight champion Jess Willard. They met at an outdoor arena in Toledo, Ohio, on July 4. The 37-year-old champ was no match for the young brawler, and Dempsey attacked fast and furiously, knocking the giant to the canvas seven times in the first round. At the end of the third round, Willard had a broken jaw, a closed eye, two broken ribs, and a partial loss of hearing. He chose not to come out of his corner for the fourth round, and Dempsey was proclaimed the heavyweight champion of the world.

Dempsey, nicknamed the Manassa Mauler, was one of the great sports stars of the 1920s. He successfully defended his title five times in four years to the refrain of record-breaking ticket sales. He employed a brutally aggressive style that has been appropriated by many champions since. Bobbing and weaving, he remained on the offensive almost continuously, swinging rights and lefts out of his crouching stance with amazing speed and power. After a memorable match against Luis Angel Firpo–the “Wild Bull of the Pampas”–in 1923, Dempsey’s promoter decided it was in the champ’s best interest to fight as infrequently as possible, thereby ensuring that excitement and profit would be high when he did. In 1924 and 1925, Dempsey was out of the ring.

Meanwhile, Gene Tunney, a scholarly former U.S. Marine with a refined boxing style, was steadily accumulating victories. The “Fighting Marine” lost sometimes, which may be why Dempsey agreed to meet Tunney for his first match in three years. On September 23, 1926, at Sesquicentennial Stadium in Philadelphia, Tunney dethroned a rusty Dempsey before 120,000 fans. Tunney never knocked Dempsey down, but he systematically accumulated enough points to win the heavyweight title in a decision after 10 rounds.

Dempsey briefly considered retiring, but in July 1927 he returned to the ring to defeat Jack Sarkey, which earned him a rematch with Tunney. On September 22, 1927, the Manassa Mauler came to Soldier Field in Chicago to regain his title. More than 100,000 spectators turned up, and there was talk that gangster Al Capone had tried to fix the fight. To avoid any possible charges of a fix, the referee was replaced at the last minute. Dave Barry, the new referee, took the boxers aside just before the match began and reminded them of a new rule that required a fighter scoring a knockdown to retreat to a neutral corner. He could not begin his count, he warned them, until the fighter on his feet started backing off to a far corner.

As the match got underway, Tunney took charge of the fight, racking up points and keeping Dempsey at bay. In the seventh round, however, the old Dempsey returned, knocking Tunney against the ropes and then felling him with three strong punches. Tunney went down, and Dempsey took a step back to the nearest corner–not a neutral corner. Barry rushed over to Dempsey and yelled, “Go to a neutral corner, Jack!” but Dempsey just stood there, glassy-eyed. Finally, Barry grabbed him and shoved him on his way. Dempsey shuffled across the ring, finally remembering the new rule that had been twice told to him before the match. Barry then began the 10-count, and Tunney got up at nine.

Tunney’s total of 14 seconds on the ground allowed him precious time to recuperate from Dempsey’s assault. He ran from his opponent for the rest of the round and then came back to dominate the eighth, even knocking Dempsey down briefly. Tunney won another decision.

Dempsey continued to box in exhibition matches until 1940, but he was never a serious contender again. He became a successful restaurateur in New York City and remained a popular figure until his death in 1983. Gene Tunney retired in 1928 after successfully defending his title against Tom Heeney. He became a wealthy business executive and died in 1978 at the age of 81. His son, John V. Tunney, was a U.S. senator.", title: "Dempsey loses on long count"},
# 8
  {category: "world", content: "The most successful and feared Confederate commerce raider of the war, the CSS Alabama, sinks after a spectacular battle off the coast of France with the USS Kearsarge.

Built in an English shipyard and sold to the Confederates in 1861, the Alabama was a state-of-the-art ship—220 feet long, with a speed of up to 13 knots. The cruiser was equipped with a machine shop and could carry enough coal to steam for 18 days, but its sails could greatly extend that time. Under its captain, Raphael Semmes, the Alabama prowled the world for three years, capturing U.S. commercial ships. It sailed around the globe, usually working out of the West Indies, but taking prizes and bungling Union shipping in the Caribbean, off Newfoundland, and around the coast of South America. In January 1863, Semmes sunk a Union warship, the Hatteras, after luring it out of Galveston, Texas. The Union navy spent an enormous amount of time and effort trying to track down the Alabama.

The ship sailed around South America, across the Pacific, and docked in India in 1864. By the summer, Semmes realized that after three years and 75,000 miles his vessel needed overhauling in a modern shipyard. He sailed around Africa to France, where the French denied him access to a dry dock. Semmes moved out of Cherbourg Harbor and found the USS Kearsarge waiting. In a spectacular battle, the Kearsarge bested and sank the Alabama. During its career, the Alabama captured 66 ships and was hunted by more than 20 Federal warships.", title: "USS Kearsarge sinks CSS Alabama"},
# 9
  {category: "world", content: "On this day in 1904, Henry Ford sets a land-speed record of 91.37 mph on the frozen surface of Michigan’s Lake St. Clair. He was driving a four-wheel vehicle, dubbed the “999,” with a wooden chassis but no body or hood. Ford’s record was broken within a month at Ormond Beach, Florida, by a driver named William K. Vanderbilt; even so, the publicity surrounding Ford’s achievement was valuable to the auto pioneer, who in June of the previous year had incorporated the Ford Motor Company, which would eventually go on to become one of America’s Big Three automakers.

Henry Ford was born on a farm in present-day Dearborn, Michigan, on July 30, 1863. In 1896, Ford, then an engineer in Detroit, built a four-wheel, self-propelled vehicle with a gasoline engine that he called the Quadricycle. Three years later, he founded the Detroit Automobile Company; however, by early 1901 the business failed. That same year, Henry Ford became involved in auto racing as a means to promote himself and gather investors for future automaking ventures. Late that year, the Henry Ford Company was established. The following year, Ford left the business after clashing with Henry Leland, who had been hired as a consultant. (Leland subsequently gave Ford’s company a new name: the Cadillac Automobile Company.)

On June 16, 1903, Ford incorporated a new company: the Ford Motor Company. In January of the following year, Ford set his record at Lake St. Clair, racing 1 mile in 39.4 seconds for a record speed of 91.37 mph. For the next several years, Ford continued to build race cars that met with varying degrees of success. In 1908, Ford launched a car for the masses, the Model T, which revolutionized the automotive industry–and American society in general–by providing affordable, reliable transportation for the average person. To promote the Model T, Ford entered it in races. In 1909, the Model T won a New York-to-Seattle race and although it was later disqualified due to a technicality, the event provided great advertising for Ford. Over the next few years, the Model T won a variety of races around the U.S. In 1913, Ford, who was reportedly unhappy with certain rules of auto racing, quit the sport. (Now that his company was a success, he didn’t require the publicity from racing anyway.)

In 1913, Ford Motor Company began employing the moving assembly line at its plant in Highland Park, Michigan, which reduced the assembly speed of a chassis from 12 hours and eight minutes to one hour and 33 minutes. The following year, Ford produced over 308,000 vehicles, more than the output of all other carmakers combined. The Model T, which was in production until 1927, became the world’s top-selling vehicle until the Volkswagen Beetle surpassed it in 1972. Henry Ford died at the age of 83 on April 7, 1947.", title: "Henry Ford sets speed record"},
# 10
  {category: "world", content: "On this day in 1965, Los Angeles Dodgers pitcher Sandy Koufax pitches the eighth perfect game in major league history, leading the Dodgers to a 1-0 win over the Chicago Cubs at Dodgers Stadium in Los Angeles.

Sandy Koufax was a talented all-around athlete from Borough Park in Brooklyn, New York. His first love was basketball, and he attended the University of Cincinnati on a basketball scholarship. His impressive left arm, however, attracted the attention of major league ball clubs and in 1954 he was signed by the Brooklyn Dodgers. Despite his promising talent, Koufax won just 36 games to 51 losses from 1955 to 1961, and was incredibly inconsistent, blowing hitters away one game and walking in runs the next. Finally, advice from veteran catcher Norm Sherry turned Koufax around. As Koufax recounted in his autobiography, Sherry told him to “take the grunt out of the fastball.” It worked: From 1962 to 1966, Sandy Koufax executed what are arguably the five greatest seasons by a pitcher in baseball history. His newfound control limited his walks from 4.8 per game to just 2.1, and he pitched no-hitters in three consecutive years–1962, 1963 and 1964.

On September 9, 1965, at the peak of his baseball career, Koufax took the mound against fellow lefty Bob Hendley of the Chicago Cubs, and a pitcher’s duel for the ages ensued. The Cubs were held scoreless, while the Dodgers scored just one run, in the fifth inning. Dodger Lou Johnson walked to lead off the inning, and then advanced to second on a sacrifice. He stole third and then scored when the Cubs catcher fumbled one of Hendley’s throws. As it turned out, one run was all Koufax needed to bring home the victory. His fastballs, which seemed to rise as they reached the plate, whizzed past batters. His curveball was typically devastating, buckling batters at the knees, almost always crossing the plate as a strike after following its parabolic path. As he closed in on a perfect game, Koufax faced the middle of the Cubs order. He struck out Ron Santo and Ernie Banks in the eighth before striking out the side in the ninth to secure his first perfect game.

In addition to throwing his first and only perfect game, Koufax struck out a total of 382 batters in 1965, shattering Rube Waddell’s 1904 record by 32. He retired after the 1966 season at just 30 years old because of arthritis in his elbow.

Koufax won three Cy Young Awards (1963, 1965 and 1966), all of them unanimous.

He was elected to the Hall of Fame in 1972. In 2007, the Modi’in Miracle of the Israel Baseball League made the 71-year old Koufax the final pick in the league’s inaugural player draft as a tribute to his legendary career and Jewish heritage.", title: "Sandy Koufax pitches perfect game"},
# 11
  {category: "world", content: "On this day in 1886, Apache chief Geronimo surrenders to U.S. government troops. For 30 years, the mighty Native American warrior had battled to protect his tribe’s homeland; however, by 1886 the Apaches were exhausted and hopelessly outnumbered. General Nelson Miles accepted Geronimo’s surrender, making him the last Indian warrior to formally give in to U.S. forces and signaling the end of the Indian Wars in the Southwest.

Geronimo was born in 1829 and grew up in what is present-day Arizona and Mexico. His tribe, the Chiricahua Apaches, clashed with non-Indian settlers trying to take their land. In 1858, Geronimo’s family was murdered by Mexicans. Seeking revenge, he later led raids against Mexican and American settlers. In 1874, the U.S. government moved Geronimo and his people from their land to a reservation in east-central Arizona. Conditions on the reservation were restrictive and harsh and Geronimo and some of his followers escaped. Over the next decade, they battled federal troops and launched raids on white settlements. During this time, Geronimo and his supporters were forced back onto the reservation several times. In May 1885, Geronimo and approximately 150 followers fled one last time. They were pursued into Mexico by 5,000 U.S. troops. In March 1886, General George Crook (1829–90) forced Geronimo to surrender; however, Geronimo quickly escaped and continued his raids. General Nelson Miles (1839–1925) then took over the pursuit of Geronimo, eventually forcing him to surrender that September near Fort Bowie along the Arizona-New Mexico border. Geronimo and a band of Apaches were sent to Florida and then Alabama, eventually ending up at the Comanche and Kiowa reservation near Fort Sill, Oklahoma Territory. There, Geronimo became a successful farmer and converted to Christianity. He participated in President Theodore Roosevelt’s inaugural parade in 1905. The Apache chief dictated his autobiography, published in 1906 as Geronimo’s Story of His Life. He died at Fort Sill on February 17, 1909.", title: "Geronimo surrenders"},
# 12
  {category: "world", content: "In Music Fund Hall in Philadelphia, the first national convention of the Republican Party, founded two years before, comes to its conclusion. John Charles Fremont of California, the famous explorer of the West, was nominated for the presidency, and William Dewis Dayton of New Jersey was chosen as the candidate for the vice presidency.

In 1854, Congress moved to vote on the Kansas-Nebraska Bill, an act that would dissolve the terms of the Missouri Compromise of 1820 and allow slave or free status to be decided in the territories by popular sovereignty. When it seemed the bill would win congressional passage, the Whig Party, which could not adequately cope with the issue of slavery, disintegrated. By February 1854, anti-slavery factions of the former Whig Party had begun meeting in the upper Midwestern states to discuss the formation of a new party. One such meeting, at Ripon, Wisconsin, on March 20, 1954, is generally remembered as the founding meeting of the Republican Party.

The Republicans, who called for the abolition of slavery in all U.S. territories, rapidly gained supporters in the North, and in 1856 their first presidential candidate, John Fremont, won 11 of the 16 Northern states. By 1860, the majority of Southern states were publicly threatening secession if a Republican won the presidency. On November 6, 1860, Republican Abraham Lincoln was elected president over a divided Democratic Party, and six weeks later South Carolina formally seceded from the Union. Within six more weeks, five other Southern states had followed South Carolina’s lead. On April 12, 1861, the Civil War began when Confederate shore batteries under General P.G.T. Beauregard opened fire on Fort Sumter in South Carolina’s Charleston Bay.

The Civil War firmly identified the Republican Party as the official party of the victorious North. After the war, the Republican-dominated Congress forced a radical Reconstruction policy on the South, which saw the passage of the 13th, 14th, and 15th Amendments to the Constitution, abolishing slavery and granting voting rights to African American men in the South. By 1876, the Republican Party had lost control of the South, but it continued to dominate the presidency, with a few intermissions, until the ascendance of Franklin D. Roosevelt in 1933.", title: "First Republican national convention ends"},
# 13
  {category: "world", content: "American pilot Charles A. Lindbergh lands at Le Bourget Field in Paris, successfully completing the first solo, nonstop transatlantic flight and the first ever nonstop flight between New York to Paris. His single-engine monoplane, The Spirit of St. Louis, had lifted off from Roosevelt Field in New York 33 1/2 hours before.

Charles Augustus Lindbergh, born in Detroit in 1902, took up flying at the age of 20. In 1923, he bought a surplus World War I Curtiss “Jenny” biplane and toured the country as a barnstorming stunt flyer. In 1924, he enrolled in the Army Air Service flying school in Texas and graduated at the top of his class as a first lieutenant. He became an airmail pilot in 1926 and pioneered the route between St. Louis and Chicago. Among U.S. aviators, he was highly regarded.

In May 1919, the first transatlantic flight was made by a U.S. hydroplane that flew from New York to Plymouth, England, via Newfoundland, the Azores Islands, and Lisbon. Later that month, Frenchman Raymond Orteig, an owner of hotels in New York, put up a purse of $25,000 to the first aviator or aviators to fly nonstop from Paris to New York or New York to Paris. In June 1919, the British fliers John W. Alcock and Arthur W. Brown made the first nonstop transatlantic flight, flying 1,960 miles from Newfoundland to Ireland. The flight from New York to Paris would be nearly twice that distance.

Orteig said his challenge would be good for five years. In 1926, with no one having attempted the flight, Orteig made the offer again. By this time, aircraft technology had advanced to a point where a few thought such a flight might be possible. Several of the world’s top aviators–including American polar explorer Richard Byrd, French flying ace Rene Fonck–decided to accept the challenge, and so did Charles Lindbergh.

Lindbergh convinced the St. Louis Chamber of Commerce to sponsor the flight, and a budget of $15,000 was set. The Ryan Airlines Corporation of San Diego volunteered to build a single-engine aircraft to his specifications. Extra fuel tanks were added, and the wing span was increased to 46 feet to accommodate the additional weight. The main fuel tank was placed in front of the cockpit because it would be safest there in the event of a crash. This meant Lindbergh would have no forward vision, so a periscope was added. To reduce weight, everything that was not utterly essential was left out. There would be no radio, gas gauge, night-flying lights, navigation equipment, or parachute. Lindbergh would sit in a light seat made of wicker. Unlike other aviators attempting the flight, Lindbergh would be alone, with no navigator or co-pilot.

The aircraft was christened The Spirit of St. Louis, and on May 12, 1927, Lindbergh flew it from San Diego to New York, setting a new record for the fastest transcontinental flight. Bad weather delayed Lindbergh’s transatlantic attempt for a week. On the night of May 19, nerves and a newspaperman’s noisy poker game kept him up all night. Early the next morning, though he hadn’t slept, the skies were clear and he rushed to Roosevelt Field on Long Island. Six men had died attempting the long and dangerous flight he was about to take.

At 7:52 a.m. EST on May 20, The Spirit of St. Louis lifted off from Roosevelt Field, so loaded with fuel that it barely cleared the telephone wires at the end of the runway. Lindbergh traveled northeast up the coast. After only four hours, he felt tired and flew within 10 feet of the water to keep his mind clear. As night fell, the aircraft left the coast of Newfoundland and set off across the Atlantic. At about 2 a.m. on May 21, Lindbergh passed the halfway mark, and an hour later dawn came. Soon after, The Spirit of St. Louis entered a fog, and Lindbergh struggled to stay awake, holding his eyelids open with his fingers and hallucinating that ghosts were passing through the cockpit.

After 24 hours in the air, he felt a little more awake and spotted fishing boats in the water. At about 11 a.m. (3 p.m. local time), he saw the coast of Ireland. Despite using only rudimentary navigation, he was two hours ahead of schedule and only three miles off course. He flew past England and by 3 p.m. EST was flying over France. It was 8 p.m. in France, and night was falling.

At the Le Bourget Aerodrome in Paris, tens of thousands of Saturday night revelers had gathered to await Lindbergh’s arrival. At 10:24 a.m. local time, his gray and white monoplane slipped out of the darkness and made a perfect landing in the air field. The crowd surged on The Spirit of St. Louis, and Lindbergh, weary from his 33 1/2-hour, 3,600-mile journey, was cheered and lifted above their heads. He hadn’t slept for 55 hours. Two French aviators saved Lindbergh from the boisterous crowd, whisking him away in an automobile. He was an immediate international celebrity.

President Calvin Coolidge dispatched a warship to take the hero home, and “Lucky Lindy” was given a ticker-tape parade in New York and presented with the Congressional Medal of Honor. His place in history, however, was not complete.

In 1932, he was the subject of international headlines again when his infant son, Charles Jr., was kidnapped, unsuccessfully ransomed, and then found murdered in the woods near the Lindbergh home. German-born Bruno Richard Hauptmann was convicted of the crime in a controversial trial and then executed. Then, in the late 1930s and early 1940s, Lindbergh became a spokesperson for the U.S. isolationism movement and was sharply criticized for his apparent Nazi sympathies and anti-Semitic views. After the outbreak of World War II, the fallen hero traveled to the Pacific as a military observer and eventually flew more than two dozen combat missions, including one in which he downed a Japanese aircraft. Lindbergh’s war-time service largely restored public faith in him, and for many years later he worked with the U.S. government on aviation issues. In 1954, President Dwight D. Eisenhower appointed him brigadier general in the Air Force Reserve. He died in Hawaii in 1974.

", title: "Lindbergh lands in Paris"},
# 14
  {category: "world", content: "Near Kitty Hawk, North Carolina, Orville and Wilbur Wright make the first successful flight in history of a self-propelled, heavier-than-air aircraft. Orville piloted the gasoline-powered, propeller-driven biplane, which stayed aloft for 12 seconds and covered 120 feet on its inaugural flight.

Orville and Wilbur Wright grew up in Dayton, Ohio, and developed an interest in aviation after learning of the glider flights of the German engineer Otto Lilienthal in the 1890s. Unlike their older brothers, Orville and Wilbur did not attend college, but they possessed extraordinary technical ability and a sophisticated approach to solving problems in mechanical design. They built printing presses and in 1892 opened a bicycle sales and repair shop. Soon, they were building their own bicycles, and this experience, combined with profits from their various businesses, allowed them to pursue actively their dream of building the world’s first airplane.

After exhaustively researching other engineers’ efforts to build a heavier-than-air, controlled aircraft, the Wright brothers wrote the U.S. Weather Bureau inquiring about a suitable place to conduct glider tests. They settled on Kitty Hawk, an isolated village on North Carolina’s Outer Banks, which offered steady winds and sand dunes from which to glide and land softly. Their first glider, tested in 1900, performed poorly, but a new design, tested in 1901, was more successful. Later that year, they built a wind tunnel where they tested nearly 200 wings and airframes of different shapes and designs. The brothers’ systematic experimentations paid off–they flew hundreds of successful flights in their 1902 glider at Kill Devils Hills near Kitty Hawk. Their biplane glider featured a steering system, based on a movable rudder, that solved the problem of controlled flight. They were now ready for powered flight.

In Dayton, they designed a 12-horsepower internal combustion engine with the assistance of machinist Charles Taylor and built a new aircraft to house it. They transported their aircraft in pieces to Kitty Hawk in the autumn of 1903, assembled it, made a few further tests, and on December 14 Orville made the first attempt at powered flight. The engine stalled during take-off and the plane was damaged, and they spent three days repairing it. Then at 10:35 a.m. on December 17, in front of five witnesses, the aircraft ran down a monorail track and into the air, staying aloft for 12 seconds and flying 120 feet. The modern aviation age was born. Three more tests were made that day, with Wilbur and Orville alternately flying the airplane. Wilbur flew the last flight, covering 852 feet in 59 seconds.

During the next few years, the Wright brothers further developed their airplanes but kept a low profile about their successes in order to secure patents and contracts for their flying machines. By 1905, their aircraft could perform complex maneuvers and remain aloft for up to 39 minutes at a time. In 1908, they traveled to France and made their first public flights, arousing widespread public excitement. In 1909, the U.S. Army’s Signal Corps purchased a specially constructed plane, and the brothers founded the Wright Company to build and market their aircraft. Wilbur Wright died of typhoid fever in 1912; Orville lived until 1948.

The historic Wright brothers’ aircraft of 1903 is on permanent display at the National Air and Space Museum in Washington, D.C.", title: "First airplane flies"},
# 15
  {category: "world", content: "At Auburn Prison in New York, the first execution by electrocution in history is carried out against William Kemmler, who had been convicted of murdering his lover, Matilda Ziegler, with an axe.

Electrocution as a humane means of execution was first suggested in 1881 by Dr. Albert Southwick, a dentist. Southwick had witnessed an elderly drunkard “painlessly” killed after touching the terminals of an electrical generator in Buffalo, New York. In the prevalent form of execution at the time–death by hanging–the condemned were known to hang by their broken necks for up to 30 minutes before succumbing to asphyxiation.

In 1889, New York’s Electrical Execution Law, the first of its kind in the world, went into effect, and Edwin R. Davis, the Auburn Prison electrician, was commissioned to design an electric chair. Closely resembling the modern device, Davis’ chair was fitted with two electrodes, which were composed of metal disks held together with rubber and covered with a damp sponge. The electrodes were to be applied to the criminal’s head and back.

On August 6, 1890, William Kemmler became the first person to be sent to the chair. After he was strapped in, a charge of approximately 700 volts was delivered for only 17 seconds before the current failed. Although witnesses reported smelling burnt clothing and charred flesh, Kemmler was far from dead, and a second shock was prepared. The second charge was 1,030 volts and applied for about two minutes, whereupon smoke was observed coming from the head of Kemmler, who was clearly deceased. An autopsy showed that the electrode attached to his back had burned through to the spine.

Dr. Southwick applauded Kemmler’s execution with the declaration, “We live in a higher civilization from this day on,” while American inventor George Westinghouse, an innovator of the use of electricity, remarked, “They would have done better with an axe.”", title: "First execution by electric chair"},
# 16
  {category: "world", content: "The members of the Dalton Gang stage an unsuccessful train robbery near Alila, California–an inauspicious beginning to their careers as serious criminals.

Bob, Emmett, and Grat Dalton were only three of Lewis and Adeleine Dalton’s 10 sons. The brothers grew up on a succession of Oklahoma and Kansas homesteads during the post-Civil War period, when the region was awash in violence lingering from the war and notorious outlaw bands like the James-Younger Gang. Still, the majority of the Dalton boys became law-abiding citizens, and one of the older brothers, Frank, served as a deputy U.S. marshal.

Ironically, Frank’s position in law enforcement brought his younger brothers into lives of crime. When Oklahoma whiskey runners murdered Frank in 1887, Grat took Frank’s place as a deputy marshal and recruited Emmett and Bob as assistants. Disillusioned by the fate of their older law-abiding brother, the three Dalton boys showed little respect for the law and began rustling cattle and horses to supplement their income. The brothers soon began to use their official law enforcement powers for their own ends, and in 1888, they killed a man for pursuing Bob’s girlfriend.

Such gross abuses of authority did not escape attention for long. By 1890, all three men were discredited as lawmen, though they managed to escape imprisonment. Taking up with some of the same hardcore criminals they had previously sworn to bring to justice, the Daltons decided to expand their criminal operations. Bob and Grat headed to California, leaving Emmett behind in Oklahoma because they felt he was still too young for a life of serious crime. In California, they planned to link up with their brother Bill and become bank and train robbers.

The Dalton Gang’s first attempt at train robbery was a fiasco. On February 6, 1891, Bob, Grat, and Bill tried to rob a Southern Pacific train near Alila, California. While Bill kept any passengers from interfering by shooting over their heads, Bob and Grat forced the engineer to show them the location of the cash-carrying express car. When the engineer tried to slip away, one of the brothers shot him in the stomach. Finding the express car on their own, Bob and Grat demanded that the guard inside open the heavy door. The guard refused and began firing down on them from a small spy hole. Thwarted, the brothers finally gave up and rode away.

The Daltons would have done well to heed the ominous signs of that first failed robbery and seek safer pursuits. Instead, they returned to Oklahoma, reunited with young Emmett, and began robbing in earnest. A year later, the gang botched another robbery, boldly attempting to hit two Coffeyville, Kansas, banks at the same time. Townspeople caught them in the act and killed Bob, Grat, and two of their gang members. Emmett was seriously wounded and served 14 years in prison.

Of all the criminal Dalton brothers, only Emmett lived into old age. Freed from prison in 1907, he married and settled in Los Angeles, where he built a successful career in real estate and contracting.", title: "Dalton Gang commits its first train robbery"},
  {category: "world", content: "On September 30, 1927, Babe Ruth hits his 60th home run of the 1927 season and with it sets a record that would stand for 34 years.

George Herman Ruth was born February 6, 1895, in Baltimore, Maryland. He was the first of eight children, but only he and a sister survived infancy. Ruth’s father was a saloon keeper on Baltimore’s waterfront, and the young George, known as “Gig” (pronounced with soft g’s) to his family, was known as a troublemaker from an early age. At seven, his truancy from school led his parents to declare him incorrigible, and he was sent to an orphanage, St. Mary’s Industrial School for Boys. Ruth lived there until he was 19 in 1914, when he was signed as a pitcher by the Baltimore Orioles.

That same summer, Ruth’s contract was sold by the Orioles to the Boston Red Sox. His new teammates called him “Babe,” short for baby, for his naiveté, but his talent was already maturing, and he was almost immediately recognized as the best pitcher on one of the great teams of the 1910s. He set a record between 1916 and 1918 with 29 2/3 consecutive scoreless innings in World Series play, including a 14-inning game in 1916 in which he pitched every inning, giving up only a run in the first.

To the great dismay of Boston fans, Ruth’s contract was sold by the Red Sox to the New York Yankees before the 1920 season by Red Sox owner Harry Frazee, so that Frazee could finance the musical No, No, Nanette. Ruth switched to the outfield with the Yankees, and hit more home runs than the entire Red Sox team in 10 of the next 12 seasons. “The Sultan of Swat” or “The Bambino,” as he was alternately known, was the greatest gate attraction in baseball through the 1920s until his retirement as a player in 1935.

The 1927 season featured a fearsome Yankees lineup of power hitters known as “Murderer’s Row” that included Ruth, Lou Gehrig, Tony Lazzerri and Bob Meusel. Ruth led the American League in home runs throughout the year, but did not appear to be within reach of his record 59 home runs, set in 1921, until he hit 16 in the month of September, tying his record on September 29. On September 30, in the last game of the season, Ruth came to the plate against lefty Tom Zachary of the Washington Senators in the eighth inning. With the count at 2-1, Ruth launched a Zachary pitch high into the right-field bleachers, and then took a slow stroll around the bases as the crowd celebrated by tearing paper into confetti and throwing hats into the air. Upon assuming his position in right-field for the ninth inning, those seated in the bleachers waved hankies at the famed slugger; Ruth responded with multiple military salutes.

During Ruth’s career with the New York Yankees, the team won four World Series and seven American League pennants. After getting rid of Ruth, the Red Sox did not win a World Series until 2004, an 85-year drought known to Red Sox fans as “the Curse of the Bambino.”

Ruth died of throat cancer on August 16, 1948. His record for career home runs was not broken until Hank Aaron hit his 715th home run on April 8, 1974, 39 years later.", title: "Babe Ruth hits 60th homer of 1927 season"},

    
])


Image.create!([
  {location_id: 8, image_url: "https://motleymissions.files.wordpress.com/2015/07/rosehill-entrance-1-of-1.jpg"},
  {location_id: 8, image_url: "http://www.historycentral.com/elections/Conventions/convention.jpg"},
  {location_id: 8, image_url: "https://i.pinimg.com/originals/c0/22/3f/c0223ffb80d99b7d9b55bfdf08102127.jpg"},

  {location_id: 9, image_url: "https://c1.staticflickr.com/8/7431/16228803459_c5f53fccce_b.jpg"},
  {location_id: 9, image_url: "http://interactive.wttw.com/sites/default/files/PD4.jpg"},
  {location_id: 9, image_url: "https://c1.staticflickr.com/6/5003/5266400301_c04f04ca26_b.jpg"},

  {location_id: 10, image_url: "https://c1.staticflickr.com/4/3752/14081935229_2960b9f330_b.jpg"},
  {location_id: 10, image_url: "https://portal-ccc.s3.amazonaws.com/media/images/uic/98/n873t0g.jpg"},
  {location_id: 10, image_url: "https://cdn-images-1.medium.com/max/1600/0*MH5ebvGp136AsdU2.jpg"},

  {location_id: 11, image_url: "https://static1.squarespace.com/static/54f736c6e4b04864be30173d/56256327e4b06f8e7d70da17/56256374e4b03a644064328c/1445803589475/_64A6953.Z_2.jpg"},
  {location_id: 11, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chicago_in_Flames_by_Currier_%26_Ives%2C_1871_%28cropped%29.jpg/1200px-Chicago_in_Flames_by_Currier_%26_Ives%2C_1871_%28cropped%29.jpg"},
  {location_id: 11, image_url: "https://www.biography.com/.image/t_share/MTIwNjA4NjMzODI0MTE4Mjg0/geronimo-9309607-2-raw.jpg"},

  {location_id: 12, image_url: "http://chicagohousemuseums.org/media/museumImages/JAHHM-exterior.jpg"},
  {location_id: 12, image_url: "https://leavenworthhistory.files.wordpress.com/2015/09/leavenworth_small-1.jpg"},
  {location_id: 12, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1876_Democratic_National_Convention_-_Missouri_%28cropped%29.jpg/1200px-1876_Democratic_National_Convention_-_Missouri_%28cropped%29.jpg"},

  {location_id: 13, image_url: "http://www.chicagoarchitecture.org/wp-content/uploads/2016/02/Pittsfield-Building-Chicago-Illinois-May-2009-001a-2-1024x790.jpg"},
  {location_id: 13, image_url: "http://assets.nydailynews.com/polopoly_fs/1.2476374.1450995618!/img/httpImage/image.jpg_gen/derivatives/landscape_1200/original-globetrotters.jpg"},
  {location_id: 13, image_url: "http://stmedia.startribune.com/images/ows_149523690955161.jpg"},

  {location_id: 14, image_url: "https://c1.staticflickr.com/5/4043/4377589204_859dcfa809_b.jpg"},
  {location_id: 14, image_url: "https://i.pinimg.com/originals/da/fc/4f/dafc4f645f826f13120e4b47f91ce0fd.jpg"},
  {location_id: 14, image_url: "https://cdn.nybooks.com/wp-content/uploads/2015/07/salter_1-081315.jpg"},

  {location_id: 15, image_url: "http://chicagopatterns.com/wp-content/uploads/2014/07/pilgrim_rendering-900x675.jpg"},
  {location_id: 15, image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Palace_of_Mechanic_Arts%2C_1893_World_Columbian_Exposition.jpg"},
  {location_id: 15, image_url: "http://stuffnobodycaresabout.com/wp-content/uploads/2015/08/first-electric-chair-Auburn-NY-photo-International-News.jpg"},

  {location_id: 16, image_url: "https://cdn.vox-cdn.com/thumbor/A5_q82cYqwdK01yEzLQgZbIZudw=/0x0:640x480/1200x800/filters:focal(264x186:366x288)/cdn.vox-cdn.com/uploads/chorus_image/image/53012583/16_09489585_0_1485822810.0.jpg"},
  {location_id: 16, image_url: "https://i.pinimg.com/originals/5b/a7/92/5ba792ab49c4b25ab375a3795b8da893.jpg"},
  {location_id: 16, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Dalton_Gang_memento_mori_1892.jpg/1200px-Dalton_Gang_memento_mori_1892.jpg"},

  {location_id: 17, image_url: "http://www.urbanremainschicago.com/wordpress/wp-content/uploads/2015/12/20151219-20151219-IMG_8082.jpg"},
  {location_id: 17, image_url: "https://i.pinimg.com/originals/69/29/54/6929549d322b49e1c6d322ee0e6613f8.jpg"},
  {location_id: 17, image_url: "https://s3.amazonaws.com/ghostsofdc/wp-content/uploads/2012/08/27170318/Babe-Ruth-at-bat.jpeg"}

])



LocationStory.create!([
  {location_id: 8, story_id: 8, source: "location origins"},
  {location_id: 9, story_id: 9, source: "location origins"},
  {location_id: 10, story_id: 10, source: "location origins"},
  {location_id: 11, story_id: 11, source: "location origins"},
  {location_id: 12, story_id: 12, source: "location origins"},
  {location_id: 13, story_id: 13, source: "location origins"},
  {location_id: 14, story_id: 14, source: "location origins"},
  {location_id: 15, story_id: 15, source: "location origins"},
  {location_id: 16, story_id: 16, source: "location origins"},
  {location_id: 17, story_id: 17, source: "location origins"},


  {location_id: 8, story_id: 18, source: "Chicago Event"},
  {location_id: 9, story_id: 19, source: "Chicago Event"},
  {location_id: 10, story_id: 20, source: "Chicago Event"},
  {location_id: 11, story_id: 21, source: "Chicago Event"},
  {location_id: 12, story_id: 22, source: "Chicago Event"},
  {location_id: 13, story_id: 23, source: "Chicago Event"},
  {location_id: 14, story_id: 24, source: "Chicago Event"},
  {location_id: 15, story_id: 25, source: "Chicago Event"},
  {location_id: 16, story_id: 26, source: "Chicago Event"},
  {location_id: 17, story_id: 27, source: "Chicago Event"},





  {location_id: 8, story_id: 28, source: "World Event"},
  {location_id: 9, story_id: 29, source: "World Event"},
  {location_id: 10, story_id: 30, source: "World Event"},
  {location_id: 11, story_id: 31, source: "World Event"},
  {location_id: 12, story_id: 32, source: "World Event"},
  {location_id: 13, story_id: 33, source: "World Event"},
  {location_id: 14, story_id: 34, source: "World Event"},
  {location_id: 15, story_id: 35, source: "World Event"},
  {location_id: 16, story_id: 36, source: "World Event"},
  {location_id: 17, story_id: 37, source: "World Event"}

])