# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Location.all.each do |location|
#   location.destroy 
# end 

# require 'unirest'
#     response = Unirest.get("https://data.cityofchicago.org/resource/fpx9-pjqk.json")
#     locations = response.body
#     locations.each do |location|
#       Location.create!(
#                                 name: location['landmark_name'],
#                                 address: location['address'],
#                                 latitude: location['latitude'],
#                                 longitude: location['longitude'],
#                                 year: location['date_built']
#                                 )
#     end 
# User.create!([
#   {name: "Alex ", email: "alex@gmail.com", password: "password", password_confirmation: "password"},
#   {name: "Joe Cool", email: "joe@gmail.com", password: "password", password_confirmation: "password"}
# ])

# require 'unirest'
#     response = Unirest.get("https://data.cityofchicago.org/resource/fpx9-pjqk.json")
#     locations = response.body
#     locations.each do |location|
#       Location.create!(
#                                 name: location['landmark_name'],
#                                 address: location['address'],
#                                 latitude: location['latitude'],
#                                 longitude: location['longitude'],
#                                 year: location['date_built']
#                                 )
#STORY ORIGIN 

# Story.create!([
#             {category: 0, title: "Charles Turzak House", content: "This design, which represents one of the earliest works by internationally recognized architect Bruce Goff, stands in pronounced contrast to traditional residences of the period. Designed as the home and studio for artist Charles Turzak and his family, it incorporated many features that did not typically appear in residential architecture until more than a decade later, including a carport, corner picture windows, and overhanging balconies. Goff also designed the Bachman House, another Chicago Landmark."},
#             {category: 0, title: "Lion House - Lincoln Park Zoo", content: "Located in one of the country's oldest municipal zoological parks, the lion house blends both the grandly-scaled public architecture of the classical style with the innovative Prairie style developed by Chicago architects in the early 20th century. The building was designed by important architect Dwight H Perkins, an advocate of park and school reforms. The building has excellent brickwork and terra-cotta ornament, unique lion mosaics, and a grand interior with a vaulted Guastavino-tile ceiling, an innovative construction technology of the time"},
#             {category: 0, title: "333 North Michigan Building", content: "Though it is known by its Michigan Avenue address, 333 North Michigan Avenue looks like it desperately wants to be one of the Wacker Drive crowd. Its narrow Wacker frontage features an 11-story tower section, while Michigan Avenue is left with the supporting wing. The intersection of Michigan Avenue and the Chicago River is the most highly prized piece of real estate in the city. These lots were claimed more than a hundred years ago by companies with timeless names like Tribune and Wrigley. 333 North Michigan Avenue doesn’t have a pedigree, but it still dates from that age. It was the last-built of the four original spectacular skyscrapers erected at this intersection, and is based on a losing entry for the Tribune Tower contest. Art Deco in form and materials, limestone and polished marble are used on the exterior. With its rounded corners and extreme streamlining, this could almost be an Art Moderne creation. Like all proper Art Deco buildings, this one features a series of exterior reliefs. In this case, they were executed by Fred M. Torrey, and honor the development of Chicago at this, the intersection where it was founded."},
#             {category: 0, title: "Charles N. Loucks House", content: "Designed as a 'model home' and published in Tabor's Modern Homes in 1891, this Queen Anne-style house was built for Irving Park land developer Charles N. Loucks. It is a fine example of 'pattern book architecture,' which were building designs sold through the mail. This was a popular method used to keep pace with housing demands in the rapidly-growing railroad suburbs of the time. The house is noteworthy for its colored beveled-glass windows, verandah with beaded spindle-work, applied metal ornament and distinctive turret.
#                 "},
#             {category: 0, title: "Chicago Harbor Lighthouse", content: "With the activation of Chicago Harbor Lighthouse, the 1859 iron lighthouse, then known as Chicago River Lighthouse, was discontinued. Its lens was disassembled, boxed up, and shipped to Detroit. The skeletal iron tower was taken apart during June and July of 1894, and all parts were newly marked with white lead, punch, or chisel, so they could be reassembled as part of the new tower at Rawley Point, Wisconsin.The original fog signal houses that flanked Chicago Harbor Lighthouse were constructed of heavy framing lumber, which was covered with two-inch planking and then sheathed in corrugated iron. The structures measured eleven by twenty-four feet, and each housed engines and boilers to operate a ten-inch steam whistle. The whistles were in operation roughly 400 hours per year, though a report in 1904 record that they were in operation that year for “some 1,293 hours and consumed about 83 tons of coal and 10 cords of wood.” Sound deflectors were placed behind the whistles in 1901, and in 1912, oil engines were installed to drive a ten-inch compressed air chime whistle, that gave a three-second blast every thirty seconds. On June 12, 1917, Congress appropriated $88,000 for relocating Chicago Harbor Lighthouse. The existing breakwater had been extended southward, and a second breakwater was being constructed south of it. The War Department had agreed to build a stone and timber crib at the south end of the north arm of the new breakwater to serve as the foundation pier for the Harbor Lighthouse, along with foundations for minor lights at the ends of the southern breakwater."},
#             {category: 0, title: "Lorraine Hansberry House", content: "For its associations with the Chicago Black Renaissance literary movement and iconic 20th-century African American playwright Lorraine Hansberry, the Lorraine Hansberry House possesses exceptional historic and cultural significance. Although subject to a racially-discriminatory housing covenant, this building was purchased in 1937 by African-American real estate developer Carl Hansberry. Despite threats, Hansberry moved his family into the building and waged a three-year-long battle culminating in a U.S. Supreme Court decision that was an important victory in the effort to outlaw racially-restrictive housing covenants. Hansberry's daughter, pioneering playwright Lorraine Hansberry, drew inspiration from this traumatic experience when writing A Raisin in the Sun. This groundbreaking play was the first drama by an African-American woman to be produced on Broadway."},
#             {category: 0, title: "LaSalle Street Cable Car Powerhouse", content: "The LaSalle Street Cable Car Powerhouse is a rare surviving artifact of Chicago's cable car system, which at its peak in the 1890s was the largest in the country, operating thousands of cable cars over 82 miles of track. The powerhouse was built by the North Chicago Street Railroad Company organized by Charles Tyson Yerkes, the leading transit entrepreneur in Chicago during the late 19th century. At the height of his influence, Yerkes controlled eight separate street railway companies and 250 miles of track in the city. The powerhouse was constructed to house engines that moved two miles of cable through channels laid in streets on the Near North Side and in the Loop business district. Those cables, in turn, pulled the thousands of cable cars that, at the peak of their operation, brought approximately 100,000 workers into downtown Chicago each day. The LaSalle Street Cable Car Powerhouse helped make possible the rapid development of the city's outlying North Side neighborhoods during one of the greatest boom periods in the history of Chicago."}
    

#     ])


# Chicago stories 
# Story.create!([
#             {category: 1, title: "1939", content: "It might seem absolutely inconceivable that there was a time in Chicago in which a fascist rally would attract thousands of people. But on June 18, 1939, the American flag and Nazi swastika banner flew side by side in what is now known as Merrimac Park. Chicago newspapers estimated that between 4,000 and 8,000 assembled to support the German-American Bund, an organization whose stated mission was to 'defend the Constitution, Flag, and Institutions of these United States of America.' But as at other Bund gatherings, those that spoke showed nothing but contempt for American democracy. There was remarkably little ideological difference between the German-American Bund and the Nazi Party in Germany. Several hundred men and boys dressed in uniforms resembling those worn by Nazi storm troopers. Vendors sold beer, brats, and anti-Semitic literature. At least 100 police officers were kept on reserve in case of a riot, but the only disturbance of the day involved a handful of brownshirts who had confiscated the film of a newspaper photographer. 
#                 The crowd would be safe from hearing from the groups it wished to eliminate from American society. Praising Adolf Hitler, Bund leader Fritz Kuhn appealed to the enthusiastic crowd to carry on his organization's 'patriotic fight' to 'free America.' The event, which began with 'The Star-Spangled Banner,'' ended with a Hitler salute and German hymns. The story of Nazism in Chicago began nearly 15 years earlier with the foundation of the Chicago chapter of the Teutonia Society, a group made up of working-class German immigrants who supported the National Socialist Party in Germany. Its national leader, a Chicago printer named Fritz Gissebl, would eventually end up as a high-ranking SS officer in Nazi-occupied Poland, although the group functioned more as a Hitler fan club and anti-Semitic drinking society than a fearsome political organization. When it disbanded in 1932, it had only about 500 members nationwide. 

#                 The Nazi party's seizure of power breathed new life into the movement. In July 1933, the Friends of New Germany held its first convention in Chicago, with the grandiose goal of unifying the millions of German-Americans under its banner. The group was no less hostile to Jews or leftists than were its counterparts in Germany. The historian Sander A. Diamond has suggested that skilled workers left economically insecure by the Depression formed the core of its membership. By April 1934, the Chicago chapter reportedly had 500 members, including 40 storm troopers that performed military drills each Thursday.

#                 Although new members took an oath that affirmed the Führerprinzip—the principle that the leader's word was above any written law—the Friends of New Germany was such a fractious mess that the German government, which had long collaborated with the group, ordered German nationals to resign their memberships in October 1935. In March 1936, the German-American Bund was formed. Kuhn, a Detroit chemist and naturalized American citizen who had proven himself a skilled organizer, was elevated as its leader. The new American führer was able to bring stability to the project of spreading Nazism in the United States, projecting the illusion that it was a rapidly expanding mass movement. 'His bombast, propensity for exaggeration, and lies were part of his technique,' Diamond writes.

#                 The Bund did not go unchallenged in Chicago. In September 1937, the Chicago Daily Times ran a ten-part series on the group. Two German-American brothers, James and John Metcalfe, went undercover and quickly rose in its ranks. Backed by the Bund's own malignant propaganda, they characterized the organization as an 'alien army' that considered not only Jews and Communists as its enemies, but also the Catholic Church and New Deal liberals. One Bundist told John Metcalfe that he had witnessed 'men dumped out of windows and killed' in Germany. 'The day will come over here when Jews get the same treatment on the street they get in Germany,' he said. The exposé intensified pressure for the federal government to investigate the group, particularly its ties to the German government.

#                 While the group continued to portray itself as a deeply patriotic organization, its actions showed an alarming contempt for democratic traditions. At a meeting at the Germania Club in Lincoln Park that drew 1,000 participants in February 1938, William Kunze, the head of the Bund's publicity office, declared that Jews, representing 4 percent of the population, controlled the press, radio, movie studios, schools, courts, and finance. Asked how the Bund proposed 'to eliminate the Jews,' Kunze urged that legislation could be passed along the lines of those that excluded Asian immigration to the United States, adding that this might not be necessary 'if the Jew learns his lesson.' During the meeting, a storm trooper from Glenview smashed a reporter's camera. Two students were assaulted when they refused to salute the Nazi flag.

#                 In October 1938, German-Americans and Czech-Americans protested a Bund celebration of the Nazi annexation of the Sudetenland. Demonstrators attempting to bring an American flag into the hall were beaten by Bundists. As the streets around the hall filled with 5,000-plus demonstrators, more than 150 police officers were called in to prevent a possible riot. 'We are not worried about those who want to break up our little volksfest,' Kuhn told his comrades."},
#                 {category: 1, title: "1912", content: "Some people have an irrational fear of clowns, but for Chicagoans of the early 20th century, the fear was probably justified. In 1912, a one-legged murderous clown was on the loose. 

# That fall, wealthy heiress Sophie Singer and her fiancé moved to Chicago from Baltimore, into a house with another couple, a circus-performing duo that went by the name the Conways. Charles Conway—whose real name was Charles Cramer—was a clown who had at some point lost one of his legs in a circus accident, and walked on a wooden leg he fashioned himself. 

# The Conways were con artists, who made their living off whatever they could mooch off others. When the heiress decided Chicago life might not be for her, the housemates’ relationship turned sour. One day, Singer’s fiance, Will, came home from a day of gambling to find the door to the rooming house barricaded and its lock stuffed. When he broke down the door, he found Sophie, who had been strangled to death with the clown’s handkerchief. Her jewelry was gone. 

# The Conways (or rather, the Cramers) were soon caught in Charles’ hometown in Ohio. The story made national news. The trial, in 1913, was also covered in papers across the country. And it did include some tomfoolery, as Chicago-based author and tour guide Adam Selzer writes on his blog, Mysterious Chicago:

# In the midst of confessing, he did a bit of clowning with reporters and police. ‘Say, Captain?’ he asked. ‘Do you know that in this case you can't hang a man with a wooden leg?’ When the Captain said he'd never heard of a law like that, Cramer said ‘You have to use a rope!’

# Charles and his wife were convicted, Charles for life. But he didn’t serve his full term. In 1925—despite his presumed lack of running agility—he managed to escape from the prison farm he was working on. He was last spotted in 1929."},

#                     {category: 1, title: "1928", content: "Born in the town of Galati Mamertino in Sicily on November 23, 1891, Antonio Lombardo immigrated to the United States in the early 20th century where he became a successful wholesale grocery business owner in Chicago, Illinois. A long time Mafia associate, Lombardo became Al Capone's advisor after John Torrio retired in 1925.

# Lombardo tried unsuccessfully to negotiate peace between the Chicago Outfit and the North Side Gang during the four-year gang war, suggesting that Capone surrender supposed Dean O'Banion assassins Albert Anselmi and John Scalise, which Capone refused. Lombardo, with the help of Capone, later became President of the Unione Siciliana in November 1925, attempting to regain control of the unstable organization as well as instituting reforms, including opening membership to non-Sicilian Italian immigrants (such as the Neapolitan Capone) and changing the organization's name to the Italo-American National Union.

# Lombardo's reforms, however, caused some resentment within Unione Siciliana members. With the partnership of Al Capone and New York gangster Frankie Yale worsening, possibly due to the end of payoffs from the Unione Siciliana to Yale, Lombardo was challenged for the Presidency by Joe Aiello, supported by Yale, in January 1928.

# Lombardo, however, refused to resign and continued to organize civic projects under the Unione Siciliana until shortly before his death on September 7, 1928. Lombardo was gunned down, along with his bodyguard Joseph Ferrara (although bodyguard Joe Lolordo survived), allegedly by an alliance of the Joe Aiello Gang and the North Side Gang, at the intersections of Madison Street and Dearborn Street. It was said that Moran ordered this death and had his two experienced gunman do the job with the help of Aiello. Thought to be retaliation for the murder of Frankie Yale the previous July, Lombardo's death was in turn soon avenged with the murder of members of the Joe Aiello Gang and the St. Valentine's Day Massacre, in 1929. He is buried in Mount Carmel Cemetery in Hillside, Illinois.

# Only one gunman was identified in Lombardo's death: a Frank Marco aka Marlo who was killed in New York City February 17, 1931; a possible unknown accomplice to Marco was killed September 9, 1928 in Michigan.[4] Another suspect was Pietro La Mantia"},
#                     {category: 1, title: "1891", content: "On this date Chicago began its 94-year reign as the nation's Second City. The 1,099,850 souls the United States Census counted in Chicago represented a 119 percent increase over the city's population just 10 years earlier. The landmark tally made Chicago second only to New York in size, a status the city held until it was eclipsed by Los Angeles in 1984.

# Not only did the size of Chicago change in that decade but so did its face and its flavor. 'Everyone had just come from somewhere--usually from the across the ocean--and all the world was going somewhere else,' wrote Edith Abbott in 'The Tenements of Chicago.' 'Here were the most foreign newspapers, the foreign banks, the steamship companies--Italian in one section, Greek in another . . . that made these areas not unlike a series of foreign cities brought together.'A chunk of the city's growth came from annexation. Six months before the census, voters in a 120-square-mile area outside the city announced they wanted in. But the most significant increase came from immigrants, who made up about 40 percent of the city's population in 1890. Immigration from northern and western Europe had been an important source of the city's population growth for decades, but by the 1890s, many newcomers originated from the countries of central, eastern and southern Europe.
# Drawn to Chicago because of its reputation abroad as a place with well-paying industrial jobs or because relatives already lived in the city, they often arrived with notes in English pinned to their clothes asking that they be directed to their brother's or their uncle's address. Others headed from the train station with their small bundles to one of the ethnic churches that became beachheads for all manner of newcomer.

# By 1897 the Greek community--the largest in the nation, both then and a hundred years later--had its first permanent Greek Orthodox parish, Holy Trinity Church, on what became known as the Greek Delta at Halsted and Harrison Streets. The Greeks had either the good fortune or the good sense to center their community in the front yard of Jane Addams' Hull House, the first settlement house in the nation. Other settlement houses soon sprang up to help immigrants adjust to their new lives, including Erie Neighborhood House, which began as a Presbyterian church in 1870 and served impoverished Germans and Scandinavians in Chicago's West Town neighborhood.

# Erie was among the settlement houses that survived, and its new clientele, mostly Hispanic immigrants, tells the continuing story of newcomers to Chicago.

# At the turn of the century, nine out of 10 immigrants were from Europe. In the 1990s, immigrants to Chicago came from three distinct regions--Latin America, Europe and Asia. The top countries of origin were Mexico, Poland and the Philippines. In 1990 the government counted 878,000 immigrants in metropolitan Chicago, only slightly fewer than the 900,000 who lived in the area in 1910. And Edith Abbott, who found the ethnic media flourishing at the turn of the century, could just as easily have been writing about 1996, when there were more than one hundred ethnic newspapers and radio and television stations, from African to Ukrainian, whose Chicago area audience numbered 1 million."},
#                     {category: 1, title: "1893", content: "The World's Columbian Exposition (the official shortened name for the World's Fair: Columbian Exposition, also known as the Chicago World's Fair and Chicago Columbian Exposition) was a world's fair held in Chicago in 1893 to celebrate the 400th anniversary of Christopher Columbus's arrival in the New World in 1492. The centerpiece of the Fair, the large water pool, represented the long voyage Columbus took to the New World. Chicago bested New York City; Washington, D.C.; and St. Louis for the honor of hosting the fair. The Exposition was an influential social and cultural event and had a profound effect on architecture, sanitation, the arts, Chicago's self-image, and American industrial optimism.

# The layout of the Chicago Columbian Exposition was, in large part, designed by John Wellborn Root, Daniel Burnham, Frederick Law Olmsted and Charles B. Atwood. It was the prototype of what Burnham and his colleagues thought a city should be. It was designed to follow Beaux Arts principles of design, namely French neoclassical architecture principles based on symmetry, balance, and splendor. The color of the material generally used to cover the buildings facades gave the fairgrounds its nickname, the White City. Many prominent architects designed its 14 'great buildings'. Artists and musicians were featured in exhibits and many also made depictions and works of art inspired by the exposition.

# The exposition covered more than 600 acres (2.4 km2), featuring nearly 200 new (but deliberately temporary) buildings of predominantly neoclassical architecture, canals and lagoons, and people and cultures from 46 countries. More than 27 million people attended the exposition during its six-month run. Its scale and grandeur far exceeded the other world's fairs, and it became a symbol of the emerging American Exceptionalism, much in the same way that the Great Exhibition became a symbol of the Victorian era United Kingdom.

# Dedication ceremonies for the fair were held on October 21, 1892, but the fairgrounds were not actually opened to the public until May 1, 1893. The fair continued until October 30, 1893. In addition to recognizing the 400th anniversary of the discovery of the New World by Europeans, the fair also served to show the world that Chicago had risen from the ashes of the Great Chicago Fire, which had destroyed much of the city in 1871.

# On October 9, 1893, the day designated as Chicago Day, the fair set a world record for outdoor event attendance, drawing 751,026 people. The debt for the fair was soon paid off with a check for $1.5 million (equivalent to $40.9 million in 2017).[5] Chicago has commemorated the fair with one of the stars on its municipal flag."},
#                     {category: 1, title: "1909", content: "The Burnham Plan is a popular name for the 1909 Plan of Chicago, co-authored by Daniel Burnham and Edward H. Bennett. It recommended an integrated series of projects including new and widened streets, parks, new railroad and harbor facilities, and civic buildings. Though only portions of the plan were realized, the document reshaped Chicago's central area and was an important influence on the new field of city planning.

# The project was begun in 1906 by the Merchants Club, which merged with the Commercial Club of Chicago, a group of prominent businessmen who recognized the necessity of improvements to the fast-growing city. They retained Daniel H. Burnham, an architect who had managed the construction of the 1893 World's Columbian Exposition in Chicago. After the fair, he had presented ideas for improving Chicago's lakefront, and had worked on city plans for Washington, D.C., Cleveland, San Francisco, and Manila and Baguio in the Philippines. Burnham retained Edward Bennett as co-author, and a small staff to help prepare the plan. Charles Moore edited the finished manuscript, and renderer Jules Guérin created several birds-eye views for the full-color document, which was printed in lavish book form and presented to the city in July 1909."},
#                     {category: 1, title: "1887", content: "On May 1, 1886, Chicago unionists, reformers, socialists, anarchists, and ordinary workers combined to make the city the center of the national movement for an eight-hour day. Between April 25 and May 4, workers attended scores of meetings and paraded through the streets at least 19 times. On Saturday, May 1, 35,000 workers walked off their jobs. Tens of thousands more, both skilled and unskilled, joined them on May 3 and 4. Crowds traveled from workplace to workplace urging fellow workers to strike. Many now adopted the radical demand of eight hours' work for ten hours' pay. Police clashed with strikers at least a dozen times, three with shootings.
#                         At the McCormick reaper plant, a long-simmering strike erupted in violence on May 3, and police fired at strikers, killing at least two. Anarchists called a protest meeting at the West Randolph Street Haymarket, advertising it in inflammatory leaflets, one of which called for “Revenge!”

#                         The crowd gathered on the evening of May 4 on Des Plaines Street, just north of Randolph, was peaceful, and Mayor Carter H. Harrison, who attended, instructed police not to disturb the meeting. But when one speaker urged the dwindling crowd to “throttle” the law, 176 officers under Inspector John Bonfield marched to the meeting and ordered it to disperse.

#                         Then someone hurled a bomb at the police, killing one officer instantly. Police drew guns, firing wildly. Sixty officers were injured, and eight died; an undetermined number of the crowd were killed or wounded.

#                         The Haymarket bomb seemed to confirm the worst fears of business leaders and others anxious about the growing labor movement and radical influence in it. Mayor Harrison quickly banned meetings and processions. Police made picketing impossible and suppressed the radical press. Chicago newspapers publicized unsubstantiated police theories of anarchist conspiracies, and they published attacks on the foreign-born and calls for revenge, matching the anarchists in inflammatory language. The violence demoralized strikers, and only a few well-organized strikes continued.
#                         Many Americans were outraged at the verdicts, but legal appeals failed. Two death sentences were commuted, but on November 11, 1887, four defendants were hanged in the Cook County jail; one committed suicide. Hundreds of thousands turned out for the funeral procession of the five dead men. In 1893, Governor John Peter Altgeld granted the three imprisoned defendants absolute pardon, citing the lack of evidence against them and the unfairness of the trial.

#                         Inspired by the American movement for a shorter workday, socialists and unionists around the world began celebrating May 1, or “May Day,” as an international workers' holiday. In the twentieth century, the Soviet Union and other Communist countries officially adopted it. The Haymarket tragedy is remembered throughout the world in speeches, murals, and monuments. American observance was strongest in the decade before World War I. During the Cold War, many Americans saw May Day as a Communist holiday, and President Eisenhower proclaimed May 1 as “Loyalty Day” in 1955. Interest in Haymarket revived somewhat in the 1980s.

#                         A monument commemorating the “Haymarket martyrs” was erected in Waldheim Cemetery in 1893. In 1889 a statue honoring the dead police was erected in the Haymarket. Toppled by student radicals in 1969 and 1970, it was moved to the Chicago Police Academy."}
                   
#     ])
# National story ____________________--
# Story.create!([
#                 {category: 2, title: "1939", content: "At 4:45 a.m., some 1.5 million German troops invade Poland all along its 1,750-mile border with German-controlled territory. Simultaneously, the German Luftwaffe bombed Polish airfields, and German warships and U-boats attacked Polish naval forces in the Baltic Sea. Nazi leader Adolf Hitler claimed the massive invasion was a defensive action, but Britain and France were not convinced. On September 3, they declared war on Germany, initiating World War II.

# To Hitler, the conquest of Poland would bring Lebensraum, or “living space,” for the German people. According to his plan, the “racially superior” Germans would colonize the territory and the native Slavs would be enslaved. German expansion had begun in 1938 with the annexation of Austria and then continued with the occupation of the Sudetenland and then all of Czechoslovakia in 1939. Both had been accomplished without igniting hostilities with the major powers, and Hitler hoped that his invasion of Poland would likewise be tolerated.

# To neutralize the possibility that the USSR would come to Poland’s aid, Germany signed a nonaggression pact with the Soviet Union on August 23, 1939. In a secret clause of the agreement, the ideological enemies agreed to divide Poland between them. Hitler gave orders for the Poland invasion to begin on August 26, but on August 25 he delayed the attack when he learned that Britain had signed a new treaty with Poland, promising military support should it be attacked. To forestall a British intervention, Hitler turned to propaganda and misinformation, alleging persecution of German-speakers in eastern Poland. Fearing imminent attack, Poland began to call up its troops, but Britain and France persuaded Poland to postpone general mobilization until August 31 in a last ditch effort to dissuade Germany from war.

# Shortly after noon on August 31, Hitler ordered hostilities against Poland to begin at 4:45 a.m. the next morning. At 8 p.m. on August 31, Nazi S.S. troops wearing Polish uniforms staged a phony invasion of Germany, damaging several minor installations on the German side of the border. They also left behind a handful of dead concentration camp prisoners in Polish uniforms to serve as further evidence of the supposed Polish invasion, which Nazi propagandists publicized as an unforgivable act of aggression.

# At 4:45 a.m. on September 1, the invasion began. Nazi diplomats and propagandists scrambled to head off hostilities with the Western powers, but on September 2 Britain and France demanded that Germany withdraw by September 3 or face war. At 11 p.m. on September 3, the British ultimatum expired, and 15 minutes later British Prime Minister Neville Chamberlain went on national radio to solemnly announce that Britain was at war with Germany. Australia, New Zealand, and India followed suit shortly thereafter. At 5:00 p.m., France declared war on Germany.

# In Poland, German forces advanced at a dizzying rate. Employing a military strategy known as the blitzkrieg, or “lightning war,” armored divisions smashed through enemy lines and isolated segments of the enemy, which were encircled and captured by motorized German infantry while the panzer tanks rushed forward to repeat the pattern. Meanwhile, the sophisticated German air force–the Luftwaffe–destroyed Polish air capability, provided air support for the blitzkrieg, and indiscriminately bombed Polish cities in an effort to further terrorize the enemy.

# The Polish army was able to mobilize one million men but was hopelessly outmatched in every respect. Rather than take a strong defensive position, troops were rushed to the front to confront the Germans and were systematically captured or annihilated. In a famously ill-fated strategy, Polish commanders even sent horsed cavalry into battle against the heavy German armor. By September 8, German forces had reached the outskirts of Warsaw, having advanced 140 miles in the first week of the invasion.

# The Polish armed forces hoped to hold out long enough so that an offensive could be mounted against Germany in the west, but on September 17 Soviet forces invaded from the east and all hope was lost. The next day, Poland’s government and military leaders fled the country. On September 28, the Warsaw garrison finally surrendered to a relentless German siege. That day, Germany and the USSR concluded an agreement outlining their zones of occupation. For the fourth time in its history, Poland was partitioned by its more powerful neighbors.

# Despite their declaration of war against Germany, Britain and France did little militarily to aid Poland. Britain bombed German warships on September 4, but Chamberlain resisted bombing Germany itself. Though Germans kept only 23 divisions in the west during their campaign in Poland, France did not launch a full-scale attack even though it had mobilized over four times that number. There were modest assaults by France on its border with Germany but these actions ceased with the defeat of Poland. During the subsequent seven months, some observers accused Britain and France of waging a “phony war,” because, with the exception of a few dramatic British-German clashes at sea, no major military action was taken. However, hostilities escalated exponentially in 1940 with Germany’s April invasion of Norway and May invasion of the Low Countries and France.

# In June 1941, Hitler attacked the USSR, breaking his nonaggression with the Soviet Union, and Germany seized all of Poland. During the German occupation, nearly three million Polish Jews were killed in the Nazi death camps. The Nazis also severely persecuted the Slavic majority, deporting and executing Poles in an attempt to destroy the intelligentsia and Polish culture. A large Polish resistance movement effectively fought against the occupation with the assistance of the Polish government-in-exile. Many exiled Poles also fought for the Allied cause. The Soviets completed the liberation of Poland in 1945 and established a communist government in the nation.”"},
#                 {category: 2, title: "1912", content: "At 2:20 a.m. on April 15, 1912, the British ocean liner Titanic sinks into the North Atlantic Ocean about 400 miles south of Newfoundland, Canada. The massive ship, which carried 2,200 passengers and crew, had struck an iceberg two and half hours before.

# On April 10, the RMS Titanic, one of the largest and most luxurious ocean liners ever built, departed Southampton, England, on its maiden voyage across the Atlantic Ocean. The Titanic was designed by the Irish shipbuilder William Pirrie and built in Belfast, and was thought to be the world’s fastest ship. It spanned 883 feet from stern to bow, and its hull was divided into 16 compartments that were presumed to be watertight. Because four of these compartments could be flooded without causing a critical loss of buoyancy, the Titanic was considered unsinkable. While leaving port, the ship came within a couple of feet of the steamer New York but passed safely by, causing a general sigh of relief from the passengers massed on the Titanic‘s decks. On its first journey across the highly competitive Atlantic ferry route, the ship carried some 2,200 passengers and crew.

# After stopping at Cherbourg, France, and Queenstown, Ireland, to pick up some final passengers, the massive vessel set out at full speed for New York City. However, just before midnight on April 14, the RMS Titanic failed to divert its course from an iceberg and ruptured at least five of its hull compartments. These compartments filled with water and pulled down the bow of the ship. Because the Titanic‘s compartments were not capped at the top, water from the ruptured compartments filled each succeeding compartment, causing the bow to sink and the stern to be raised up to an almost vertical position above the water. Then the Titanic broke in half, and, at about 2:20 a.m. on April 15, stern and bow sank to the ocean floor.

# Because of a shortage of lifeboats and the lack of satisfactory emergency procedures, more than 1,500 people went down in the sinking ship or froze to death in the icy North Atlantic waters. Most of the 700 or so survivors were women and children. A number of notable American and British citizens died in the tragedy, including the noted British journalist William Thomas Stead and heirs to the Straus, Astor, and Guggenheim fortunes.

# One hour and 20 minutes after Titanic went down, the Cunard liner Carpathia arrived. The survivors in the lifeboats were brought aboard, and a handful of others were pulled out of the water. It was later discovered that the Leyland liner Californian had been less than 20 miles away at the time of the accident but had failed to hear the Titanic‘s distress signals because its radio operator was off duty.

# Announcement of details of the tragedy led to outrage on both sides of the Atlantic. In the disaster’s aftermath, the first International Convention for Safety of Life at Sea was held in 1913. Rules were adopted requiring that every ship have lifeboat space for each person on board, and that lifeboat drills be held. An International Ice Patrol was established to monitor icebergs in the North Atlantic shipping lanes. It was also required that ships maintain a 24-hour radio watch.

# On September 1, 1985, a joint U.S.-French expedition located the wreck of the Titanic lying on the ocean floor at a depth of about 13,000 feet. The ship was explored by manned and unmanned submersibles, which shed new light on the details of its sinking."},
#                 {category: 2, title: "1928", content: "Leon Trotsky, a leader of the Bolshevik revolution and early architect of the Soviet state, is deported by Soviet leader Joseph Stalin to Alma-Ata in remote Soviet Central Asia. He lived there in internal exile for a year before being banished from the USSR forever by Stalin.

# Born in the Ukraine of Russian-Jewish parents in 1879, Trotsky embraced Marxism as a teenager and later dropped out of the University of Odessa to help organize the underground South Russian Workers’ Union. In 1898, he was arrested for his revolutionary activities and sent to prison. In 1900, he was exiled to Siberia.

# In 1902, he escaped to England using a forged passport under the name of Leon Trotsky (his original name was Lev Davidovich Bronshtein). In London, he collaborated with Bolshevik revolutionary Vladimir Ilyich Lenin but later sided with the Menshevik factions that advocated a democratic approach to socialism. With the outbreak of the Russian Revolution of 1905, Trotsky returned to Russia and was again exiled to Siberia when the revolution collapsed. In 1907, he again escaped.

# During the next decade, he was expelled from a series of countries because of his radicalism, living in Switzerland, Paris, Spain, and New York City before returning to Russia at the outbreak of the revolution in 1917. Trotsky played a leading role in the Bolsheviks’ seizure of power, conquering most of Petrograd before Lenin’s triumphant return in November.

# Appointed Lenin’s secretary of foreign affairs, he negotiated with the Germans for an end to Russian involvement in World War I. In 1918, he became war commissioner and set about building up the Red Army, which succeeded in defeating anti-Communist opposition in the Russian Civil War. In the early 1920s, Trotsky seemed the heir apparent of Lenin, but he lost out in the struggle of succession after Lenin fell ill in 1922.

# In 1924, Lenin died, and Joseph Stalin emerged as leader of the USSR. Against Stalin’s stated policies, Trotsky called for a continuing world revolution that would inevitably result in the dismantling of the Soviet state. He also criticized the new regime for suppressing democracy in the Communist Party and for failing to develop adequate economic planning. In response, Stalin and his supporters launched a propaganda counterattack against Trotsky. In 1925, he was removed from his post in the war commissariat. One year later, he was expelled from the Politburo and in 1927 from the Communist Party. In January 1928, Trotsky began his internal exile in Alma-Ata and the next January was expelled from the Soviet Union outright.

# He was received by the government of Turkey and settled on the island of Prinkipo, where he worked on finishing his autobiography and history of the Russian Revolution. After four years in Turkey, Trotsky lived in France and then Norway and in 1936 was granted asylum in Mexico. Settling with his family in a suburb of Mexico City, he was found guilty of treason in absentia during Stalin’s purges of his political foes. He survived a machine-gun attack on his home but on August 20, 1940, fell prey to a Spanish Communist, Ramon Mercader, who fatally wounded him with an ice-ax. He died from his wounds the next day."},
#                 {category: 2, title: "1891", content: "The members of the Dalton Gang stage an unsuccessful train robbery near Alila, California–an inauspicious beginning to their careers as serious criminals.

# Bob, Emmett, and Grat Dalton were only three of Lewis and Adeleine Dalton’s 10 sons. The brothers grew up on a succession of Oklahoma and Kansas homesteads during the post-Civil War period, when the region was awash in violence lingering from the war and notorious outlaw bands like the James-Younger Gang. Still, the majority of the Dalton boys became law-abiding citizens, and one of the older brothers, Frank, served as a deputy U.S. marshal.

# Ironically, Frank’s position in law enforcement brought his younger brothers into lives of crime. When Oklahoma whiskey runners murdered Frank in 1887, Grat took Frank’s place as a deputy marshal and recruited Emmett and Bob as assistants. Disillusioned by the fate of their older law-abiding brother, the three Dalton boys showed little respect for the law and began rustling cattle and horses to supplement their income. The brothers soon began to use their official law enforcement powers for their own ends, and in 1888, they killed a man for pursuing Bob’s girlfriend.

# Such gross abuses of authority did not escape attention for long. By 1890, all three men were discredited as lawmen, though they managed to escape imprisonment. Taking up with some of the same hardcore criminals they had previously sworn to bring to justice, the Daltons decided to expand their criminal operations. Bob and Grat headed to California, leaving Emmett behind in Oklahoma because they felt he was still too young for a life of serious crime. In California, they planned to link up with their brother Bill and become bank and train robbers.

# The Dalton Gang’s first attempt at train robbery was a fiasco. On February 6, 1891, Bob, Grat, and Bill tried to rob a Southern Pacific train near Alila, California. While Bill kept any passengers from interfering by shooting over their heads, Bob and Grat forced the engineer to show them the location of the cash-carrying express car. When the engineer tried to slip away, one of the brothers shot him in the stomach. Finding the express car on their own, Bob and Grat demanded that the guard inside open the heavy door. The guard refused and began firing down on them from a small spy hole. Thwarted, the brothers finally gave up and rode away.

# The Daltons would have done well to heed the ominous signs of that first failed robbery and seek safer pursuits. Instead, they returned to Oklahoma, reunited with young Emmett, and began robbing in earnest. A year later, the gang botched another robbery, boldly attempting to hit two Coffeyville, Kansas, banks at the same time. Townspeople caught them in the act and killed Bob, Grat, and two of their gang members. Emmett was seriously wounded and served 14 years in prison.

# Of all the criminal Dalton brothers, only Emmett lived into old age. Freed from prison in 1907, he married and settled in Los Angeles, where he built a successful career in real estate and contracting."},
#                 {category: 2, title: "1893", content: "On this day in 1893, the largest land run in history begins with more than 100,000 people pouring into the Cherokee Strip of Oklahoma to claim valuable land that had once belonged to Native Americans. With a single shot from a pistol the mad dash began, and land-hungry pioneers on horseback and in carriages raced forward to stake their claims to the best acres.

# Ironically, not many years before that same land had once been considered worthless desert. Early explorers of Oklahoma believed that the territory was too arid and treeless for white settlement, but several suggested it might be the perfect place to resettle Indians, whose rich and fertile lands in the southeast were increasingly coveted by Americans. The U.S. government later took this advice and began removing eastern Indian tribes like the Cherokee and Choctaw to Oklahoma Territory in 1817. No more eager than the whites to leave their green and well-watered lands for the arid plains, some Indians resisted and had to be removed by force-most tragically, the 4,000 Cherokee who died during the brutal overland march known appropriately as the “Trail of Tears.”

# By 1885, a diverse mixture of Native American tribes had been pushed onto reservations in eastern Oklahoma and promised that the land would be theirs “as long as the grass grows and the water runs.” Yet even this seemingly marginal land did not long escape the attention of land-hungry Americans. By the late nineteenth century, farmers had developed new methods that suddenly made the formerly reviled Plains hugely valuable. Pressure steadily increased to open the Indian lands to settlement, and in 1889, President Benjamin Harrison succumbed and threw open large areas of unoccupied Indian lands to white settlement. The giant Cherokee Strip rush was only the largest of a series of massive “land runs” that began in the 1890s, with thousands of immigrants stampeding into Oklahoma Territory and establishing towns like Norman and Oklahoma City almost overnight."},
#                 {category: 2, title: "1909", content: "On July 29, 1909, the newly formed General Motors Corporation (GM) acquires the country’s leading luxury automaker, the Cadillac Automobile Company, for $4.5 million.

# Cadillac was founded out of the ruins of automotive pioneer Henry Ford’s second failed company (his third effort, the Ford Motor Company, finally succeeded). When the shareholders of the defunct Henry Ford Company called in Detroit machinist Henry Leland to assess the company’s assets for their planned sale, Leland convinced them to stay in business. His idea was to combine Ford’s latest chassis (frame) with a single-cylinder engine developed by Oldsmobile, another early automaker. To that end, the Cadillac Car Company (named for the French explorer Antoine Laumet de La Mothe Cadillac, who founded the city of Detroit in 1701) was founded in August 1902. Leland introduced the first Cadillac–priced at $850–at the New York Auto Show the following year.

# In its first year of production, Cadillac put out nearly 2500 cars, a huge number at the time. Leland, who was reportedly motivated by an intense competition with Henry Ford, assumed full leadership of Cadillac in 1904, and with his son Wilfred by his side he firmly established the brand’s reputation for quality. Among the excellent luxury cars being produced in America at the time–including Packard, Lozier, McFarland and Pierce-Arrow–Cadillac led the field, making the top 10 in overall U.S. auto sales every year from 1904 to 1915.

# By 1909, William C. Durant had assembled Buick and Oldsmobile as cornerstones of his new General Motors Corporation, founded the year before. By the end of July, he had persuaded Wilfred Leland to sell Cadillac for $4.5 million in GM stock. Durant kept the Lelands on in their management position, however, giving them full responsibility for automotive production. Three years later, Cadillac introduced the world’s first successful electric self-starter, developed by Charles F. Kettering; its pioneering V-8 engine was installed in all Cadillac models in 1915.

# Over the years, Cadillac maintained its reputation for luxury and innovation: In 1954, for example, it was the first automaker to provide power steering and automatic windshield washers as standard equipment on all its vehicles. Though the brand was knocked out of its top-of-the-market position in the 1980s by the German luxury automaker Mercedes-Benz, it sought to reestablish itself during the following decades, and remains a leader in the luxury car market."},
#                 {category: 2, title: "1887", content: "On this day in 1887, President Grover Cleveland signs the Dawes Severalty Act into law. The act split up reservations held communally by Native American tribes into smaller units and distributed these units to individuals within the tribe. Also called the General Allotment Act, the law changed the legal status of Native Americans from tribal members to individuals subject to federal laws and dissolved many tribal affiliations The Dawes Severalty/General Allotment Act constituted a huge blow to tribal sovereignty.

# Cleveland’s goal was to encourage Native Americans to integrate into American agrarian culture. Cleveland, who once said though the people support the government; the government should not support the people, led a socially reformist yet financially conservative government that did not believe in welfare handouts. He signed the act in a sincere but misguided attempt to improve the Native Americans’ lives by incorporating them into white culture, rejecting earlier policies toward Native Americans that forced them to live on desolate reservations where it was difficult to make a living. However, his support of the Dawes Severalty Act actually did more damage than good.

# Under the Dawes Act, the head of each Native American family received 160 acres in an effort to encourage Native Americans to take up farming, live in smaller family units that were considered more American and renounce tribal loyalties. The government held such lands in trust for 25 years, until the recipients could prove themselves self-sufficient farmers. Before the family could sell their allotment, they were required to get a certificate of competency. If the family did not succeed at farming, the land reverted back to the federal government for sale, usually to white settlers. The Dawes Act reduced Native American landholdings from 138 million acres in 1887 to 78 million in 1900 and continued the trend of white settlement on previously Native American-held land. In addition, the law created federally funded boarding schools designed to assimilate Native American children into white society. Family and cultural ties were practically destroyed by the now-notorious boarding schools, in which children were punished for speaking their native language or performing native rituals.

# The Dawes Severalty Act was finally abolished in 1934, during President Franklin Roosevelt’s first term."}
          
#     ])

# locationStory ______________
# LocationStory.create!([
#                 {location_id: 1, story_id: 1},
#                 {location_id: 2, story_id: 2},
#                 {location_id: 3, story_id: 3},
#                 {location_id: 4, story_id: 4},
#                 {location_id: 5, story_id: 5},
#                 {location_id: 6, story_id: 6},
#                 {location_id: 7, story_id: 7}



#     ])
    # locations.each do |location|
    #   puts "ID: #{location['id']}"
    #   puts "Name: #{location['landmark_name']}"
    #   puts "Year built: #{location['date_built']}"
    #   puts ""
    #   puts "Adress: #{location['address']}"
    #   puts "Latitude: #{location['latitude']}"
    #   puts "Longitude: #{location['longitude']} "
    #   puts ""
    #   puts "-" * 50
    #   puts ""
    # end
#   end
# Location.create!([
#               {name: "Charles Turzak House", address: "7059 N Olcott Ave", latitude: "42.0095630785", longitude: "-87.813251935", year: "1938-39"},
#               {name: "Lion House - Lincoln Park Zoo", address: "2132 N Stockton Dr", latitude: "41.92133817", longitude: "-87.6333359813", year: "1912"},
#               {name: "Charles Turzak House", address: "7059 N Olcott Ave", latitude: "42.0095630785", longitude: "-87.813251935", year: "1938-39"},
#               {name: "Charles Turzak House", address: "7059 N Olcott Ave", latitude: "42.0095630785", longitude: "-87.813251935", year: "1938-39"},
#               {name: "Charles Turzak House", address: "7059 N Olcott Ave", latitude: "42.0095630785", longitude: "-87.813251935", year: "1938-39"},
#               {name: "Charles Turzak House", address: "7059 N Olcott Ave", latitude: "42.0095630785", longitude: "-87.813251935", year: "1938-39"},

# {location_id: 1, image_url: "http://s3.amazonaws.com/architecture-org/files/buildings/auditorium-theater-04.jpg"},

# Image.create!([
                # {location_id: 1, image_url: "http://s3.amazonaws.com/architecture-org/files/buildings/auditorium-theater-04.jpg"},
#               {location_id: 2, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ9vOSci_138OJ1Z-mBMKfaw6AabU_rwbw64DbiALtn5QDB2xhwA"},
#               {location_id: 3, image_url: "https://media.gettyimages.com/photos/interior-of-palmer-house-hotel-lobby-in-chicago-picture-id526253359"},
#               {location_id: 4, image_url: "https://res.cloudinary.com/fleetnation/image/private/c_fit,w_1120/g_south,l_text:style_gothic2:%C2%A9%20Sherlon%20Gerard,o_20,y_10/g_center,l_watermark4,o_25,y_50/v1445991127/x2gmlke78mcxich0e7ks.jpg"},
#              {location_id: 5, image_url: "http://www.roadarch.com/12/7/cmchouse2.jpg"},
#               {location_id: 6, image_url: "https://c1.staticflickr.com/8/7187/6864366131_8bcb6be7b2_b.jpg"}
#                   ])



# Story.create!([
#                 {category: 1, content: "The crowning achievement of his career was the department store that he designed in 1899 for Schlesinger and Mayer, which was later bought by Carson Pirie Scott & Co. The ornate, cast-iron ornamentation around the windows on the first two floors serves as a richly flowing picture frame meant to accentuate the merchandise on display."},
#                 {category: 0, content: "Founded in 1889 as a social settlement, Hull-House played a vital role in redefining American democracy in the modern age. Addams and the residents of Hull-House helped pass critical legislation and influenced public policy on public health and education, free speech, fair labor practices, immigrants’ rights, recreation and public space, arts, and philanthropy. Hull-House has long been a center of Chicago’s political and cultural life, establishing Chicago’s first public playground and public art gallery, helping to desegregate the Chicago Public Schools, and influencing philanthropy and culture."},
#                 {category: 1, content: "The first (known as 'The Palmer') was built as a wedding present from Potter Palmer to his bride Bertha Honoré. It opened on September 26, 1871, but burned down just 13 days later on October 9, 1871 in the Great Chicago Fire. Palmer immediately set to work rebuilding, and with a $1.7 million signature loan (believed to be the largest individual loan ever secured at that time), constructed one of the fanciest hotels worldwide in postfire Chicago."},
#                 {category: 1, content: "From 1912 to 1917, the Fine Arts Building housed the Chicago Little Theatre, an art theater credited with beginning the Little Theatre Movement in the United States. Not being able to afford rental on the building's 500-seat auditorium, co-producers Maurice Browne and Ellen Van Volkenburg rented a large storage space on the fourth floor at the back and built it out into a 91-seat house."},
#                 {category: 2, content: "Founded in 1889 as a social settlement, Hull-House played a vital role in redefining American democracy in the modern age. Addams and the residents of Hull-House helped pass critical legislation and influenced public policy on public health and education, free speech, fair labor practices, immigrants’ rights, recreation and public space, arts, and philanthropy. Hull-House has long been a center of Chicago’s political and cultural life, establishing Chicago’s first public playground and public art gallery, helping to desegregate the Chicago Public Schools, and influencing philanthropy and culture."},
#                {category: 2, content: "Architect Bruce Goff created a neighborhood sensation in 1948, when he remodeled a modest wood house (built in 1889) into the home and studio for recording engineer Myron Bachman. The window openings were changed and an exterior cladding of brick and corrugated aluminum was added. It remains a local attraction, as well as a nationally recognized example of work by one of architecture's most unusual figures."},
#                 {category: 1, content: "The Nickerson House was designed by one Chicago's earliest prominent architects, Edward J. Burling (1819–1892) of Burling and Whitehouse.[3] In addition, three decorators were contracted for the interiors: William August Fiedler (1843–1903) and R. W. Bates & Co. of Chicago, and New York-based George A. Schastey & Co. The three-story, 24,000 square-foot Nickerson House was reported to be the largest and most extravagant private residence in Chicago at the time of its completion. (This distinction would be transferred to the Palmer Mansion on the Gold Coast several years later.) Nickerson spared no expense, spending $450,000 on the construction and decoration of his home"},

#                         ])


#LocationStory.create!([
#               {location_id: 1, story_id: 1, source: "Auditorium Hall"},
#               {location_id: 2, story_id: 2, source: "Jane Addams' Hull House and Dining Hall"},
#               {location_id: 3, story_id: 3, source: "Palmer House Hotel"},
#               {location_id: 4, story_id: 4, source: "Fine Arts Building"},
#               {location_id: 5, story_id: 5, source: "Myron Bachman House"},
#               {location_id: 6, story_id: 6, source: "Samuel M. Nickerson House"}
#                   ])

